

The model
=========

We now generalize the contest game introduced by @moldovanu2001optimal to a situation where players simultaneously decide $i)$ the quality and $ii)$ how fast to produce a given output. Then we explore the problem of revenue maximization faced by a contest designer with preferences for both quality and time.

Basic setup
-----------


Equilibrium
-----------

In this section, we solve the model for the unique symmetric Bayesian Nash equilibrium of players. 


### Tournament

At equilibrium, players choose $\quality$ and $t_i$ by maximizing \eqref{expected payoffs} given their beliefs about the equilibrium actions of the other players. 

The key to characterization of the equilibrium is that $t_i=\deadline$ is a (weakly) dominant strategy for each player. Indeed, any time strictly below the deadline does not affect the probability of winning but is costly in terms of effort, and any time strictly above the deadline gives a negative payoff. 

Since players should avoid playing weakly dominated strategies, we have that $t_i=\deadline$ for every $i=1,...,n$. Then it can be shown that, at equilibrium, the optimal quality is a one-to-one transformation of a player's ability according to some "bidding" function $b(\cdot)$. Hence, $Y_i = b(A_i)$. Since the distribution of $A_i$ is known, one can use a change of variables formula to express the probability of winning in \eqref{expected payoffs} in terms of the distribution $F$. Then, the first order condition of $\pi$ with respect to quality gives the following differential equation in $\ability$ (for every $i=1,...,n$):

$$
	\sum_{k=1}^{q} \hat p^\prime_{k}(\phi(y_i)\mid \tournament) \phi^\prime(y_i) v_k 
		= \beta y_i^{\beta-1} a^\alpha t^\gamma
$$

with the boundary condition $y(\lotype)=0$. 

At equilibrium we have $a=\phi(y)$. Thus, the differential equation is separable. After rearranging, we have:

$$	
	\sum_{k=1}^{q}\phi(y_i)^{-\alpha}\hat p^\prime_{k}(\phi(y_i)\mid \tournament)\phi^\prime(y_i) v_k 
		= \beta y_i^{\beta-1}  t^\gamma.
$$

Integration of both sides with respect to $\phi$ gives:

$$	
	\int_{0}^{y} 
		\sum_{k=1}^{q} t^{-\gamma} v_k 
			\phi(x)^{-\alpha}\hat p^\prime_{k}(\phi(x)\mid \tournament)\phi^\prime(x) dx
		= 	\int_{0}^{y} \beta x^{\beta-1}   dx
$$


Using the chain rule of derivatives

$$
	\int_a^b f(g(x)) g^\prime(x) dx = \int_{g(a)}^{g(b)} f(x) dx \qquad \text{(chain rule)}
$$

the solution is 

\begin{equation} 
	\label{optimal quality tournament}
	y(a_i) = 
	\left[\deadline^{-\gamma} \sum_{k=1}^q v_k \int x^{-\alpha} \hat p^\prime_k(x)dx \right]^{1/\beta}
\end{equation}


An important property of \eqref{optimal quality tournament} is that $y(a_i)$ has its lower bound in zero and its upper bound in 

$$
	y(\hitype) = 
	\left[\deadline^{-\gamma} v_1 \left(
		\frac{\hitype^{-\alpha+1} - \lotype^{-\alpha+1}}{-\alpha + 1} 
		\right)\right]^{1/\beta}.
$$

- Monotonicity of the equilibrium output quality implies that, for every $i=1, ..., n$, the equilibrium expected payoff from the contest $\pi_i^*$ depends on the rank of the player's ability relative to the others. 

- Equilibrium payoffs do not depend on the elasticity $\beta$ or $\gamma$, but only on $\alpha$. 
- When abilities are distributed over the unit interval, the equilibrium payoff for the highest ability player is $\pi(\hitype=1) = v_1 (-\alpha)/ (1-\alpha)$. 

### Equilibrium in a race

In a similar way, one can derive the equilibrium strategy in a race. Again the key observation is that any quality below the target gives a zero probability of winning and any quality  above the target gives a constant probability of winning. Thus, player $i$'s choice of quality is either zero (with $t_i=\deadline$ by convention) or $y_i=\target$.

Then, the equilibrium xxx for player $i$ is 
\begin{equation} \label{tstar}
t^*(a_i) = 
	\ctime^{-1}
	\left[\ctime(\deadline) 
	+ \frac{1}{\cscore(\target)}
	\left(\alpha \int_{a_i}^{\hitype} A^\prime(z) dz
	  + (1-\alpha) \int_{a_i}^{\hitype} B^\prime(z)  dz
	\right)
	\right]
\end{equation}
where
\begin{equation}
  A(x) = \frac{1}{c_{a}(x)} f_{(n-1:n-1)}(x)
\end{equation}
and
\begin{equation}
	B(x) = \frac{1}{c_{a}(x)} \left\{
      		\left[1- F_{(n-1:n-1)}(x)\right]f_{(n-1:n-2)}(x)
      		+ f_{(n-1:n-1)}(x) F_{(n-1:n-2)}(x)
    \right\}.
\end{equation}

An important property of XX is that $y^*(a_i)$ has its upper bound in XX and
lower bound in XX. Again payoffs are xxxx. Hence, by setting to zero and solving for the ability, gives the marginal ability ${\underline a}$ as
\begin{equation}
  {\underline a}= h(n, V, F_A, C, d).
\end{equation}

### Tournament vs races

By comparing equilibrium xxx and xxx, we find that the race and the tournament do not (ex-post) dominate one another with respect to output quality. Whereas the race always dominates the tournament with respect to completion time. [This is only when the deadline is the same. Otherwise, there's always xxxx.] This result is stated below.

\begin{proposition}
There always exist an interval of abilities where the output quality is higher in the race than in the tournament. By contrast, every player takes less completion time in the race than in the tournament.
\end{proposition}

\begin{proof}
Marginal type has utility zero in a race but the same type has a strictly positive utility in the tournament. Since probability of winning is not different in the race or the tournament (the bid is a monotonic transformation of the individual ability or, in other words, rankings are virtually the same), expected payoffs in equilibrium differ only in the cost functions. Hence, to be an equilibrium, the player in the tournament should bid less than the player in the race to earn a strictly positive expected payoff. 
\end{proof}

Let's make an example.  
```
p <- plnorm   # pdf individual abilities 
r <- rlnorm   # Simulate individual abilities
cy <- function(x) x^2 # Cost function performance
ct <- function(x) 2*exp(1-x)  # Cost function timing 
```
FIGURE 1. Equilibrium bids in a race and a tournament. 


Implications. The above proposition applies only if the target is higher in a race than in a tournament. But what if the two competitions had the same target ? In that case, tournaments and races have the same marginal type. Therefore, the performance of players in the tournament with reserve are always non-lower than those in the race. This does not imply that it is optimal to set the target. On the contrary, we will show that it is optimal to set an optimal target in a tournament that is below the optimal target in a race. Next section.  


The contest designer's problem
---------------------------

Let us now focus on the contest designer's problem. Imagine the contest designer can choose the competition format to be either the race or the tournament. Imagine all other aspects of design are given. The prize structure $\alpha$ has been already chosen. There is a deadline $\deadline$, which is the same in both competition formats. [The quality requirement $\target^c$ in the tournament  is smalle than that in the race $\target^\race > \target^\tournament$)] We will relax this assumption later to consider a more general setting where these variables are also part of the contest designer's problem.

The contest designer has an objective function that is increasing in the expected quality of the winning solution and decreasing in the corresponding time to completion. Here, to do not complicate exposition, we assume that the contest designer cares about the winning submission only: second placed efforts are not considered. [If the principal values the diversity of the solutions ... but we assume it does not.]


XXX EQUATION XXXX

The optimal choice involves a comparison of the expected profits between the race and the tournament. Given xxxx, we can show that there will be a threshold on the cost of completion time $\hat\tau$ above which the race is a better choice than the tournament, and vice versa.

\begin{proposition}
There's a tau above which ... 
\end{proposition}

Proof.  In a tournament, the objective function is 
\begin{align}
R_\tournament & = \Pr(t_{(1:n)}\leq \deadline) \left\{\int y^*(x \mid t_{(1:n)}\leq \deadline) dF_{n:n}(x) - \tau \deadline - 1 \right\}  \nonumber\\
  & = \int_{\mtype}^{\hitype} y^*(x) dF_{n:n}(x) - \tau \deadline - 1. 
\end{align}

That is, the contest designer's objective function is the sum of the expected output quality for a given deadline, minus the cost $\tau$ of having the winner working on the task until completion (i.e., until the deadline), and the cost of the prize pool (recall the prize pool is normalized to one). 

[Implicitly, you're assuming that the prize is always large enough to ensure positive effort.] [Second prize too is stochastic!!!!]

In a race, the objective function is
\begin{align}
R_\race & =  
  \Pr(a_{(N)}\geq \mtype) \left\{\target - \alpha -
  \Pr(a_{(N-1)}\geq \mtype) (1-\alpha) \right\}
  - \tau \int_{\mtype}^{\infty} t^*(x) dF_{N:N}(x) \nonumber\\
  & = [1-F_{N:N}(\mtype)] \left\{\target - \alpha -
  [1-F_{N-1:N}(\mtype)] (1 - \alpha) \right\}
  - \tau \int_{\mtype}^{\infty} t^*(x) dF_{N:N}(x).
\end{align}


Note. $t^*(x) \leq \deadline$ for all $x$'s. Thus, a lower bound for the above objective function can be computed: 
\begin{align}
\underline {R_\race} & = 
  [1-F_{N:N}(\mtype)] \left\{\target - \alpha -
  [1-F_{N-1:N}(\mtype)] (1 - \alpha) - \tau \deadline\right\}
\end{align}
An even simpler lower bound is rewriting the above expression as if $\alpha=1$ (note if the real alpha was set 1 then also mtype would change and therefore setting alpha hits a lower bound only when mtype does xxxx  when alpha is 1). 
 
Note. $y^*(x)$ is lower than $\target$ for all $a < \mtype$. Thus, a lower bound of the tournament's expression is
\begin{align}
\overline {R_\tournament} & = 
  [1-F_{N:N}(\mtype)] \target + \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) 
  - \tau \deadline - 1. 
\end{align}

\begin{align}
  \underline {R_\race} \geq & \overline {R_\tournament} \nonumber\\
  [1-F_{N:N}(\mtype)] (\target - 1 - \tau \deadline) \geq &
  [1-F_{N:N}(\mtype)] \target + \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) 
  - \tau \deadline - 1 \nonumber\\
  - [1-F_{N:N}(\mtype)] (\tau\deadline + 1) \geq &
  \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) 
  - (\tau \deadline + 1) \nonumber\\
  F_{N:N}(\mtype) (\tau \deadline + 1) \geq &
  \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) \nonumber\\
  \tau \geq & 
    \left[
      \frac{\int_{\mtype}^\infty y^*(x) dF_{N:N}(x)}{F_{N:N}(\mtype)} -1 
    \right] \frac{1}{\deadline}
\end{align}

End proof.

When the cost of time $\tau$ is sufficiently high, the race is preferred. Interestingly, the threshold is a function of the deadline to complete the job, as xxx. It also depends on the shape of xxxx. 

### Optimal minimum-entry

Now we turn to discuss the contest designer's choice of an optimal minimum requirement $\target$. So far, we have assumed that $\target^\race>\target^\tournament$. Now, we show that the assumption that xxxx is indeed an optimal choice of the contest designer. This is summarized in the next proposition.

\begin{proposition}
Suppose the contest designer can choose the target that max profits in both the race and the tournament. Then, the optimal $\target$ in tournament is generally lower than that in a race.
\end{proposition}

To prove that it is indeed the case. We proceed in two steps. First, we assume that the contest designer does not care about minimizing the timing of the innovation by imposing $\tau = 0$. For simplicity, assume that $\alpha=1$ (winner-takes-all). In a race, this means that the optimal target will be a value that makes equal the costs in terms of less participation versus the gains in terms of higher values of the winning solutions. Formally, the contest designer's problem in a race is
\begin{align}
  \text{maximize } & R^\race = [1-F_{N:N}(\mtype)] (\target^\race - 1).
\end{align}
Note that $\mtype$ depends on the target. This is clearly concave in $\target^\race$. 
Thus, the first order condition is also sufficient. 
\begin{align}\label{foc race}
  \text{FOC } & \Rightarrow -F^\prime_{N:N}(\mtype) \mtype^\prime (\target^\race - 1) + [1-F_{N:N}(\mtype)] = 0.
\end{align}

In a tournament, ... 
\begin{align}
  \text{maximize } & R^\race = \int_{\mtype}^\infty y^*(x, \target) d F_{N:N}(x) - [1-F_{N:N}(\mtype)]. 
\end{align}
Convexity is not sure. If not, then the optimal target is zero. Which is lower than the optimal target in a race. 

Instead. If the objective function is (strictly) concave then there's an internal solution. 

\begin{align} \label{foc tournament}
  \text{FOC } \Rightarrow & 
    \frac{d\int_{\mtype}^\infty y^*(x, \target) d F_{N:N}(x)) }{d \target}
      + F^\prime_{N:N}(\mtype) \mtype^\prime =0 \nonumber\\ 
    & \text{(by using Leibniz rule)}\nonumber\\
  \Rightarrow & - y^*(\mtype, \target) \mtype^\prime F^\prime_{N:N}(\mtype) 
      + \int_{\mtype}^\infty \dystar - F^\prime_{N:N}(\mtype) \mtype^\prime = 0\nonumber\\
  \Rightarrow & -\target \mtype^\prime F^\prime_{N:N}(\mtype) 
      + \int_{\mtype}^\infty \dystar - F^\prime_{N:N}(\mtype) \mtype^\prime = 0.
\end{align}

Using \eqref{foc race} with \eqref{foc tournament}, the optimal target is the same in the race and the tournament only if
\begin{align} 
  \int_{\mtype}^\infty \dystar = [1- F_{N:N}(\mtype)].
\end{align}

\[
  \frac{\partial y^*(x, \target)}{\partial \target} = 
    \frac{c_y^\prime(\target)}{c_y^\prime(y^*(x, \target))}. 
\]

Then. 

- If $c_y(\cdot)$ is linear, we have that the ratio is one for all $x$. 

- If $c_y(\cdot)$ is convex, then we have that it is less than one. If 

- If $c_y(\cdot)$ is concave, then we have that it is higher than one.

As a result, if linear or convex the first order condition is lower than that in the race. Since the obj. function is concave (second order is decreasing), the target should be lower in a tournament than in a race to satisfy the first order condition.  (a lower target increases the focs.).

Conjecture. If $\tau>0$, the $\target$ in the race is higher. 


Structural econometric model
----------------------------

Readings: 

- [The winner's curse, reserve prices, and endogenous entry: Empirical insights from eBay auctions][ebay]

- [Entry and competition effects in first-price auctions: theory and evidence from procurement auctions][auctions]

- [Auctions with entry][entry]

[ebay]: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.199.680&rep=rep1&type=pdf 
[entry]: http://www.vita.mcafee.cc/PDF/AuctionswithEntry.pdf
[auctions]:  https://www.econstor.eu/bitstream/10419/79263/1/516364804.pdf


General two-step strategy:

- First step. Identify the marginal type from the data and the distribution of types. 

- Second step. Using the estimated distribution of types. 


Basic idea. Equilibrium condition gives:
\begin{equation}
  y_i^* = y^*(a_i; F_{\mathcal{A}}). 
\end{equation}
with $y^*(\cdot)$ being an invertible function with $\phi$ denoting the inverse.

Hence the distribution of bids is
\begin{equation}
F_{Y}(y) = \Pr(y_i^* \leq y) 
        = \Pr(y^*(a_i) \leq y) 
        = \Pr(a_i \leq \phi(y)) 
        = F_\mathcal{A}( \phi(y)).
\end{equation}

Identification of the model. suggest

