

The model
=========

In this section, we generalize the _contest game_ introduced by @moldovanu2001optimal to a situation where players allocate their effort along two dimensions: performance and time. Then we explore the problem of maximization faced by a contest designer with xxx preferences for performance and time.

Basic setup
------------

A (generalized) contest game is an $N$ player game with asymmetric information. Players compete by choosing a performance variable $y$ and a timing $t$, both nonnegative numbers --- to be thought of as the quality and time to completion of a job. Players move simultaneously to maximize the probability of winning one of $K$ available prizes while minimizing the cost of effort. Prizes are of decreasing value $V_1>V_2>...>V_K$.

Let $a_1, ..., a_N$ denote a privately observed individual ability of players drawn from a common distribution $F_{\mathcal{A}}$ on a given interval $\mathcal{A}$.  Let $C(a_i, y_i, t_i)$ denote player $i$'s cost function and assume it is multiplicative 
\begin{equation}
  C(a_i, y_i, t_i) = c_a(a_i) c_y(y_i) c_t(t_i)
\end{equation}
with $c_a(\cdot)$ and $c_t(\cdot)$ both monotonic decreasing (the higher the ability or the time to complete, the lower the cost). Whereas $c_{y}(\cdot)$ is monotonic increasing (the higher the performance, the higher the cost). To ensure nonnegative costs, we further impose the following conditions: $c_{y}(0)\geq 0$, $\lim_{t\rightarrow \infty}c_{t}(t)>0$, and $\lim_{a\rightarrow \infty}c_{a}(a)>0$.

Let $p_{i, k}(y_1,..., y_N, t_1, ..., t_N)$ be player $i$'s probability of winning the $k^{th}$ prize. Player $i$'s expected payoff is

\begin{equation}
  \pi_i = \sum_{k=1}^{K} p_{i, k}(y_1,..., y_N, t_1, ..., t_N) V_k - C(a_i, y_i, t_i). 
\end{equation}


For convenience, suppose that to win a prize it is not sufficient to beat the other competitors but players have to successfully meet a given deadline and satisfy any minimum performance requirement. Let $\deadline>0$ denote a given deadline and $\target\geq 0$ a (possibly positive) required minimum performance. 

<!-- 

The goal for each player is If the timing is above a given deadline $d>0$ or the performance is below a certain level $q>0$, the player gets zero utility. Otherwise, the player is given a rank based on his performance and timing. 
 A contest is xxxx. Ranked . 
 -->

The tournament competition corresponds to a special case where players that successfully meet the deadline (i.e., $t_i\leq\deadline$) are ranked by their performance and the probability of winning is
\begin{equation}
  xxxx.
\end{equation}

<!-- In a tournament, the agent having achieved the highest output quality within the deadline gets the first prize, the agent having achieved the second highest output quality gets the second prize, and so on. In a race, by contrast, the first agent to achieve an output quality of at least ${\bar y}$ within the deadline wins the first prize, the second to achieve the same target gets the second prize, and so on. -->

<!-- 
\begin{definition}
Let xxx denote the $N-1-k$ order statistic. A tournament is a contest game where the probability of winning the $k^{th}$ prize is 
\begin{equation}
  p_{k} = \Pr(y_i=xxxx\text{ and }t_i\leq \bar{t}). 
\end{equation}
\end{definition}
 -->

The race competition, by contrast, corresponds to a special case where players are ranked by their timing provided that the performance is above a minimum level ($y_i\geq\target$) and the probability of winning is 
\begin{equation}
  xxxx.
\end{equation}


Note the "duality" of the two competitions. [@baye2003strategic]

Note that, in both competitions, if players xxxx they get no prizes (i.e., a rank $r > K$). 


Equilibrium
-------------

To simplify the analysis, we suppose there are only two prizes of total value normalized to one. We let $\alpha$ denote the fraction going to the first place which is larger than the fraction going to the second place ($\alpha\geq1/2$).

\begin{proposition}
xxx
\end{proposition}

We provide here the symmetric equilibrium with one prize and $n>2$
agents. In appendix XXX, we provide a general formula for $k>2$ prizes.

Let $y_{1:n} < y_{2:n} < ... < y_{n:n}$ denote the order statistics of
the $y_j$’s for every $j\neq i$ and let ${F_{Y_{r:n}}}(\cdot)$ and
${f_{Y_{r:n}}}(\cdot)$ denote the corresponding distribution and density
for the $r$’th order statistic.

\begin{proposition}
In a tournament, the unique symmetric equilibrium of the model gives,
for every $i=1, ..., N$, the optimal time to completion $t^*(a_i)$ equal
to the deadline $\bar{t}$ and the optimal output quality $y^*(a_i)$ as
\begin{equation}
 \label{eq: optimal bid tournament}
  y^*(a_i) =  V_1 \int_{a_i}^\infty {f_{Y_{n:n}}} (z) dz
\end{equation}
if ${a_i}\geq \underline a$ (see @moldovanu2001optimal), and zero otherwise.
\end{proposition}

An important property of xxx is that $y^*(a_i)$ has its upper bound in xxx and
lower bound in xxxx. Also, equilibrium output quality is monotonic
increasing in the agent’s ability [see @moldovanu2001optimal]. Thus, for
every $i=1, ..., n+1$, the equilibrium expected reward depends only on
the rank of his ability relative to the others. Using ${F_{A_{r:n}}}$ to
denote the distribution of the $r$’th order statistic of abilities gives

$$\label{eq: expected payoffs tournament}
  {F_{A_{n:n}}}(a_i) V_1  - C(y_i^*, d, a_i).$$

Hence, by setting to zero and solving for the ability, gives the
marginal ability ${\underline a}$ as

$${\underline a}= h(n, V, F_A, C, d).$$


- Using 'duality' property of these games, we determine the equilibrium behavior in a race as follows: 

\begin{proposition}
  Equilibrium behavior in a race is XXXX
\end{proposition}


EXAMPLE 
```{r, echo=TRUE}
p <- plnorm   # pdf individual abilities 
r <- rlnorm   # Simulate individual abilities
cy <- function(x) x^2 # Cost function performance
ct <- function(x) 2*exp(1-x)  # Cost function timing

 
```




Contest designer's problem
---------------------------

The sponsor of the contest chooses the rules of the competition
including the prize structure $V_1$ and $V_2$, deadline $\deadline$, and target
quality $\target$. Here we focus on the decision of competition format (race or tournament) for a given $\deadline$ --- the same for everyone --- and a target $\target_\race>0$ in the race which is larger than in the tournament where it is normalized to zero (e.g., $\target_\tournament = 0$). Later we relax this assumption to consider an optimal $\target$. 

The contest designer's objective function is given by 
\begin{equation}
\begin{array}{ll}
    \mbox{maximize} & \int_{0}^{\infty} y^*(x) dF_{n:n}(x)
      - \tau \int_{0}^{\infty} t^*(x) dF_{n:n}(x) 
      - 1
  \end{array}
\end{equation}
where the expected quality of the winner and the expected time spent $T=\sum_{i=1}^{n+1} T_i$ and prizes paid $V=\sum_{j=1}^k p_{j} V_j$ (with $p_j=1$ if the prize is awarded
and $p_j=0$ otherwise).


The main result is as given by the next proposition: 

\begin{proposition}
Given x, y, z, the optimal choice for the contest design is to pick a race when 
\begin{equation}
  \tau > \frac{\Delta y^*} {\Delta t^*} 
\end{equation}
and otherwise to pick the tournament.
\end{proposition}

This result hinges on $\target_\race > 0$. Now we show that, in general, it is always optimal to set a lower target in the tournament.  Maybe this lemma should go first and then the proposition. 

\begin{lemma}
Given x,y,z, it is optimal for the contest designer to choose $\target_\race > \target_\tournament$. 
\end{lemma}



Structural econometric model
----------------------------


Identification of the model. suggest
