---
title: Regressions in Tournaments vs Races
author: Andrea Blasco
institute: ablasco@fas.harvard.edu
date: \today
output: 
#   pdf_document:
#     template: ~/Templates/Pandoc/boyd.latex
 beamer_presentation:
    slide_level: 2
    template: ~/Templates/Pandoc/boyd.beamer
---

```{r setup, include=FALSE}
library(stargazer)
knitr::opts_chunk$set(cache=TRUE)
```

# Data preparation

## Main covariates

```{r}
names(races)
```


## Missing values

```{r}
missings <- apply(races, 2, function(x) sum(is.na(x)))
missings[missings>0]
```

## Imputing missing values

```{r, echo=FALSE}
set.seed(25978) # For imputations

## Prepare data.frame with covariates only
dat <- within(races, {
	finished <- finished=='True' 
	year <- as.numeric(format(member_date, '%Y'))
	hours <- week1 + week2 + week3 + week4
	rating <- mm_rating
	rating2 <- algo_rating
	nsub <- mm_events
	nreg <- mm_reg
	nperc <- (nsub+1)/(nreg+1)
	paid  <- ifelse(is.na(paid), 0, paid)
	paid_b  <- paid > 0
	male <- gender=='Male'
	grad <- educ == "Doctorate/PhD" | educ == "Postgraduate/Master of arts"
	below30 <- age == "<20 years old" | age== "20-25 years old" | age =="26-30 years"
	# Impute missing values
	hours.imp <- impute(hours, "random")
	risk.imp <- impute(risk, "random")
	below30.imp <- impute(below30, "random")
	grad.imp <- impute(grad, "random")
	male.imp <- impute(male, "random")
	timezone.imp <- impute(timezone, "random")
}) 

## Impute ratings
impute.rating <- function(dat) {
	fit <- lm(rating ~ year + nreg + grad.imp + paid_b, data=dat)
	SIGMA <- sigma(fit); MEAN <- predict(fit)
	sim <- rnorm(length(MEAN), mean=MEAN, sd=SIGMA)
	ifelse(is.na(dat$rating), sim, dat$rating)
}
impute.volatility <- function(dat) {
	fit <- lm(volatility ~ nreg, data=dat)
	SIGMA <- sigma(fit); MEAN <- predict(fit)
	sim <- rnorm(length(MEAN), mean=MEAN, sd=SIGMA)
	ifelse(is.na(dat$volatility), sim, dat$volatility)
}

dat$rating.imp <- impute.rating(dat)
dat$volatility.imp <- impute.volatility(dat)

## Covars with missing
covars.imp <- with(dat, data.frame(year, rating.imp, volatility.imp, rating2, nreg, nsub, nperc, paid_b, nwins, ntop10, risk.imp, hours.imp, male.imp, timezone.imp, grad.imp, below30.imp))
covars <- dat[, gsub(".imp", "", names(covars.imp))]

## Compare imputed
m <- cbind(observed=apply(covars, 2, mean, na.rm=TRUE), imputed=apply(covars.imp, 2, mean,na.rm=TRUE))
round(m, 1)
```


## Correlations 

```{r, echo=FALSE}
panel.smooth<-function (x, y, col="blue", bg=NA, pch=16, cex=0.5, col.smooth = "red", span=2/3, iter=3, ...) {
  points(x, y, pch=pch, col=col, bg=bg, cex=cex)
  ok <- is.finite(x) & is.finite(y)
  if (any(ok)) 
    lines(stats::lowess(x[ok], y[ok], f=span, iter=iter), col=col.smooth, ...)
}
pairs(covars.imp, lower.panel=panel.smooth, upper.panel=NULL, pch=16, cex=.5)
```

# Exploratory Analysis

## Basic model

```{r, echo=FALSE, results='asis'}
z <- data.frame(submit=dat$submit, covars.imp)
fit <- glm(submit ~ ., data=z, quasibinomial(logit))

fit.step <- step(fit)
stargazer(fit, font.size='tiny', align=TRUE, header=FALSE, no.space=FALSE, single.row=TRUE, float=FALSE)
```
