---
endfloat: false
---

Modeling participation to the contest
======================================

```{r setup, echo=FALSE}
require(xtable)

# Data preparation
load("races.RData")
ilogit <- function(x) exp(x) / (1+exp(x))
std <- function(x) sd(x)/sqrt(length(x))

# Data
target      <- 820793.00 
baseline    <- 794084.93
entry     <- !is.na(dat$nsub)
expert.y  <- dat$mm.count > 0
top10.y   <- dat$mm.top10 > 0
yr        <- as.numeric(format(dat$msince, "%Y"))
yr.f      <- factor(format(dat$msince, "%Y"))
assgn     <- dat$treatment
educ      <- dat$educ
age       <- dat$age
```

Entry and platform experience
---------------------

```{r, echo=FALSE, fig.cap="Signed-up competitors by experience and skills. Experience is measured by the year of registration to the platform. Skills are measured by an indicator variable that is one if the competitor was ranked top 10 in one or more past competitions, and zero otherwise."}
barplot(table(top10.y, yr.f), las=2
        , main="Platform experience and skills"
        , xlab="Year of registration as member"
        , ylab="Freq."
        , legend.text=c("Never top 10", "Top 10 once")
        , args.legend = list(x = "top", bty='n'))
```


```{r, echo=FALSE, fig.width=9.5, fig.cap="Association between the probability of participating, individual experience, and skills by treatment. Dots show relative frequency of participants with high (dark dots) and low (red crosses) skills. Curves show the conditional probability predicted by a Probit model that is linear (---) or quadratic (- - -) in experience."}

f <- function(dat) {
  # Prepare data
  type      <- unique(dat$treatment)
  entry     <- !is.na(dat$nsub)
  top10.y   <- dat$mm.top10 > 0
  yr        <- as.numeric(format(dat$msince, "%Y"))
  yr.f      <- factor(format(dat$msince, "%Y"))
  # Fit the model
  fit.f <- glm(entry ~ yr.f + top10.y, family=binomial('probit'))
  d.f <- data.frame(expand.grid(top10.y=c(TRUE, FALSE)
                    , yr.f=levels(yr.f)))
  yhat.f <- predict(fit.f, newdata=d.f, type='response')

  plot(sort(unique(yr)), yhat.f[d.f$top10.y], pch=16, ylim=c(0, 1)
      , xlab="Year of registration as member"
      , ylab="Relative frequency"
      , main=sprintf("%s", type))
  points(sort(unique(yr)), yhat.f[!d.f$top10.y], pch=4, col=2)

  for (p in 1:2) {
    fit <- glm(entry ~ poly(yr,p) + top10.y, family=binomial('probit'))
    d <- data.frame(expand.grid(top10.y=c(TRUE, FALSE), yr=sort(unique(yr))))
    yhat <- predict(fit, newdata=d, type='response')

    lines(x=sort(unique(yr)), y=yhat[d$top10.y], lty=p)
    lines(x=sort(unique(yr)), y=yhat[!d$top10.y], lty=p, col=2)
  }
}

par(mfrow=c(1, 3))
f(subset(dat, treatment=="Race"))
f(subset(dat, treatment=="Tournament"))
f(subset(dat, treatment=="Reserve"))
```

Scores
-------------


Timing of submissions

```{r, echo=FALSE, results='asis'}
tab.cap <- "Daily frequency of submissions made. Each line indicates the submissions made by one competitor during the 9-day submission period by treatment. The '1' indicates that the competitor made at least one submission in that day, whereas the '.' indicates no submissions. Observations are ordered by the competitor's final score in decreasing order."

f <- function(dat) {
  index <- which(scores$id %in% dat$id)
  z <- scores[index, ]
  ord <- aggregate(subprov ~ id, z, max)
#  ord <- aggregate(subts ~ id, z, max) # last submission
  ord <- order(ord[, 2], decreasing=TRUE)
  m <- table(as.character(z$id), as.Date(z$subts))
  m[m>0] <- 1
  strings <- gsub("0", ".", apply(m, 1, paste, collapse=''))
  strings <- paste("\\texttt{", strings, "}", sep='')
  return(head(strings[ord], 25))
}

str.race <- f(subset(dat, treatment=='Race'))
str.tour <- f(subset(dat, treatment=='Tournament'))
str.targ <- f(subset(dat, treatment=='Reserve'))
tab <- cbind(Race=str.race, Tournament=str.tour, Target=str.targ)
print(xtable(tab, caption=tab.cap)
      , include.rownames=TRUE, comment=FALSE
      , sanitize.text.function=function(x) x)

```

Scores
----------

```{r, echo=FALSE, fig.cap="Association between scores and submissions by treatment."}
f <- function(dat) {
  type      <- unique(dat$treatment)
  with(dat, 
    plot(nsub, lastscore/1e5, pch=16
        , ylim=c(7.5, 8.6)
        , xlim=c(0, max(nsub,na.rm=TRUE)+15)
        , xlab="Submissions", ylab="Final score", bty='n'
        , main=type)
  ) 
  abline(h=c(target, baseline)/1e5, lty=1:2)
  text(y=c(target, baseline)/1e5, x=max(dat$nsub, na.rm=TRUE)+10, pos=1, xpd=2
      , c("Target","Baseline"))
  abline(lm(lastscore/1e5 ~ nsub, data=dat, subset=nsub>0), col=2)
#   abline(lm(lastscore/1e5 ~ nsub, data=dat, subset=nsub>0), lty=2)
}      

par(mfrow=c(1, 3))
f(subset(dat, treatment=="Race"))
f(subset(dat, treatment=="Tournament"))
f(subset(dat, treatment=="Reserve"))
```

```{r, echo=FALSE, fig.cap="Association between scores and submissions by room."}
f <- function(dat) {
  type <- unique(dat$room)
  with(dat, 
    plot(nsub, lastscore/1e5, pch=16
        , ylim=c(7.5, 8.6)
        , xlim=c(0, max(nsub,na.rm=TRUE)+15)
        , xlab="Submissions", ylab="Final score", bty='n'
        , main=type)
  ) 
  abline(h=c(target, baseline)/1e5, lty=1:2)
  text(y=c(target, baseline)/1e5, x=max(dat$nsub, na.rm=TRUE)+10, pos=1, xpd=2
      , c("Target","Baseline"))
  abline(lm(lastscore/1e5 ~ nsub, data=dat, subset=nsub>0), col=2)
}      

par(mfrow=c(6, 4), mar=c(1,1,1,1))
xlim <- range(scores$subts)
ylim <- c(7.5, 8.6)
for (i in levels(dat$room)) {
  type <- dat$treatment[which(dat$room==i)]
  ids <- subset(dat, room==i)$id
  with(subset(scores, id %in% ids)
      , plot(subts, subprov/1e5, pch=16, ylim=ylim, xlim=xlim, yaxt='n', xaxt='n'))
  abline(h=c(target, baseline)/1e5, lty=1:2)
  mtext(type, side=3, cex=0.5)
} 
```


