#!/bin/bash
current_dir=`pwd`
manuscript_dir=Manuscript
writing_dir=Writing
#resources_dir=resources
main_file=main.tex
bib_file=/Users/andrea/Papers/library.bib


if [ ! -d $manuscript_dir ]; then 
  mkdir -p $manuscript_dir/{figures,tables}
fi

# Copy files
cp $writing_dir/$main_file $manuscript_dir/mf.tex
cp $writing_dir/*.txt $manuscript_dir
cp $bib_file $manuscript_dir/refs.bib 

# Pandoc
cd $manuscript_dir
FILES=*.txt
for f in $FILES
do
  echo "Processing $f file"
  sed "s/\[^/^[/g" $f > $f~
  pandoc $f~ --natbib --bibliography=refs.bib -o ${f%.*}.tex
done
rm *~
rm $FILES


# Expand and compile
latexpand mf.tex > fullpaper.tex
pdflatex fullpaper.tex
open fullpaper.pdf

if [ "$1" == "-bib" ]
then 
  bibtex fullpaper.aux
  pdflatex fullpaper.tex
  pdflatex fullpaper.tex
  open fullpaper.pdf
fi
if [ "$1" == "-docx" ]
then
  pandoc -s fullpaper.tex -o fullpaper.docx --bibliography=refs.bib
  open fullpaper.docx
fi
if [ "$1" == "-appendix" ]
then
  pdflatex appendix.tex
  open appendix.pdf
fi
