pdf_document:
  toc: false
  keep_tex: false
  fig_crop: false
  fig_width: 7
  fig_height: 6
  fig_caption: true
  highlight: tango #kate
  template: Templates/template.latex
  includes:
    in_header: Templates/header.tex
#    before_body:   Templates/doc_prefix.tex
#    after_body:    Templates/doc_suffix.tex
  pandoc_args: [
      "--bibliography", "library.bib"
#      , "--natbib"
    ]
