
Structural econometrics
===========================

Simulate structural model
------------------------------

```{r}
p <- plnorm 
r <- rlnorm
zeroprofit <- function(a, n, c0, ...) {
  p(a, ...)^n - c0 * a^(-1)
}
marginal <- function(n, cost, ...) {
  uniroot(f=zeroprofit, n=n, c0=cost, interval=c(0.0001, 10), ...)$root
}
 
# Plot 1
old.par <- par(mfrow=c(3,3), mar=c(4,4,2,2))
for (nn in c(3, 4, 5, 8, 10, 15, 20, 30, 50)) {
  curve(zeroprofit(x, n=nn, c0=0.75), from=0.001, to=3
      , main=sprintf("n=%i",nn), ylab="R(a)", xlab="a"
      , ylim=c(-1, 1))
  abline(h=0, lty=2, col=2)
  for (ss in seq(0.5, 5, length=10))
    curve(zeroprofit(x, n=nn, c0=0.75), add=TRUE, col=gray(ss/5))
}
par(old.par)
```

Simulate estimation 
------------------------

```{r}
# Function to simulate and estimate data
estimate <- function(n, obs, n.seq) {
  costs <- seq(0.05, 0.95, length=n.seq)
  m <- matrix(ncol=4, nrow=length(costs))
  colnames(m) <- c("a", "a.hat", "a.ci95hi", "a.ci95lo")
  for (i in 1:length(costs)) {
    # Sim
    th <- marginal(n=n, cost=costs[i])
    y <- ifelse(r(obs) > th, 1, 0)
    # Fit
    fit <- glm(y ~ 1, family=binomial('probit'))
    # Save
    a.hat <- exp(-coef(fit))
    a.ci95hi <- exp(-coef(fit) + 2*coef(summary(fit))[2])
    a.ci95lo <- exp(-coef(fit) - 2*coef(summary(fit))[2])
    m[i, ] <- c(th, a.hat, a.ci95hi, a.ci95lo)
  }
  return(m)
}

# Plot 2
old.par <- par(mfrow=c(3,3), mar=c(4,4,2,2))
for (nn in c(3, 4, 5, 8, 10, 15, 20, 30, 50)) {
  m <- estimate(nn, 300, 10)
  plot(m, pch=16, ylim=range(m)
      , main=sprintf("n=%i",nn)
      , ylab="Estimated threshold", xlab="True threshold")
  segments(x0=m[,1], y0=m[, 3],y1=m[, 4])
  abline(a=0, b=1)
}
par(old.par)
````

Structural analysis of the data
----------------------------------

- Assumption: 
    * ability is distributed $a\sim F(|\theta, x_l)= \text{log-N}(0,1)$

```{r, results='asis'}

# Analysis
entry <- ifelse(is.na(dat$nsub), 0, 1)
treatment <- dat$treatment
size <- dat$size
fit <- glm(entry ~ treatment*size, family=binomial('probit'))

# Baseline (race)
bhat <- coef(fit)
race.Large <- exp(-sum(bhat[1]))
tour.Large <- exp(-sum(bhat[1:2]))
targ.Large <- exp(-sum(bhat[c(1, 3)]))
race.Small <- exp(-sum(bhat[c(1, 4)]))
tour.Small <- exp(-sum(bhat[c(1, 2, 4, 5)]))
targ.Small <- exp(-sum(bhat[c(1, 3, 4, 6)]))

tab <- rbind(Race=c(Large=race.Large, Small=race.Small)
  , Tournament=c(tour.Large, tour.Small)
  , Reserve=c(targ.Large, targ.Small))

# Estimated thresholds in ability
print(xtable(tab, caption="Estimated marginal type ($\\alpha=1$)."), comment=FALSE)
```

Estimated entry costs
---------------------------

- Recall: zero-profit condition  $\implies$ $\marginaltype=h(\alpha, n, F_A, C_0)$
- $\implies$ entry cost $C_0=f(\alpha, n, F_A, \hat\marginaltype)$

```{r, results='asis'}
# Estimated costs
zeroprofit.cost <- function(c0, n, a, ...) {
  zeroprofit(a, n, c0, ...)
}
marginal.cost <- function(n, a, ...) {
  100*uniroot(f=zeroprofit.cost, n=n, a=a, interval=c(0.0001, 0.999), ...)$root
}

tab <- rbind(Race=c(Large=marginal.cost(a=race.Large, n=15)
            , Small=marginal.cost(a=race.Small, n=10))
  , Tournament=c(Large=marginal.cost(a=tour.Large, n=15)
                , Small=marginal.cost(a=tour.Small, n=10))
  , Reserve=c(Large=marginal.cost(a=targ.Large, n=15)
              , Small=marginal.cost(a=targ.Small, n=10))
)

# Estimated Entry in ability
print(xtable(tab, caption="Estimated entry costs as \\% of prize pool."), comment=FALSE, digits=c(0, 1, 1))
```


