The model
=========

We now generalize the contest game introduced by @moldovanu2001optimal to a situation where players simultaneously decide $i)$ the quality and $ii)$ how fast to produce a given output. Then we explore the problem of revenue maximization faced by a contest designer with preferences for both quality and time.

Basic setup
------------

A generalized contest game is an n-player game with asymmetric information in which each player ($i=1,..., n$) competes against the others to win a prize. Players assign a nonnegative value $v_k$ to each prize ($k=1, ..., q$) that is decreasing in the prize rank  ($v_1\geq v_2\geq ...\geq v_q$). Each player's strategy consists in choosing an output quality $y_i$ and a timing $t_i$ both nonnegative numbers that determine player $i$'s probability  $p_{k}(y_i, t_i)$ of winning a prize $k$.

Each player incurs a production cost $c_i$ that is shaped by a cost function $C(\cdot)$ which is increasing in quality and decreasing in timing. The cost function also depends on an individual ability parameter $a_i$ that is private information of each player and that is drawn at random from a common distribution $F$ on a finite interval $[\lotype, \hitype]$ with $\lotype>0$.^[This assumption rules out common parametric distributions like the log-normal and forces us to focus the analysis on beta-type distributions. However, results do not hinge on this particular assumption.] For simplicity, we assume the cost function is multiplicative:
\begin{equation}
  C(a_i, y_i, t_i) = c_a(a_i) c_y(y_i) c_t(t_i)
\end{equation}
with $c_a(\cdot)$ and $c_t(\cdot)$ being monotonic decreasing functions (the higher the ability or the time to complete, the lower the cost) and $c_{y}(\cdot)$ being a monotonic increasing function (the higher the quality, the higher the cost). We impose additional conditions to ensure nonnegative costs
\[
	c_{a}(\hitype)>0, c_{t}(\lotype)>0, \text{ and } c_{y}(\lotype)\geq 0.
\]

Player $i$'s payoff is then

\begin{equation}
  \label{expected payoff}
  \pi_i = \sum_{k=1}^{q} p_{k}(y_i, t_i) v_k - C(a_i, y_i, t_i). 
\end{equation}

And we can denote a (generalized) contest game $G$ by 
\begin{equation}
G \equiv \left\{
    n, q, \{v_k\}_{k=1}^{q},  F, C, \{p_{k}\}_{k=1}^{q} 
  \right\}.
\end{equation}

When players have to successfully meet a given deadline and/or satisfy a minimum quality level to be eligible to win a prize, we say that the contest game $G$ has a minimum-entry requirement. Let $\deadline>0$ be the deadline and $\target\geq 0$ the required minimum performance. A game $G$ has a minimum-entry requirement when, for every prize $k$ and player $i$, the probability $p_{k}(\cdot, \cdot)=0$ when player $i$'s quality is below a target level $q_i < \target$ or the timing to completion is above a given deadline $t_i>\deadline$. To simplify exposition, we further use the convention that whenever the deadline is not met $t_i> \deadline$ then the output quality is zero $y_i=0$, and whenever the required quality is not met $y_i<\target$ then the time of completion is above the deadline $t_i = \infty$. This simply ensures that when one of the entry-requirements is not met by a player, the player has a zero probability of winning a prize. 

Using the above notation, we define a tournament as a contest game with the following characteristics. 

\begin{definition}[Tournament] \label{tournament}
Let $y_{(1:n-1)}, ..., y_{(n-1:n-1)}$ denote the order statistics of the $y$'s for the $n-1$ opponents of player $i$. A tournament is a contest game $G$ with a minimum-entry requirement $\deadline>0$ where player $i$'s probability of winning a prize is zero when $t_i > \deadline$. Otherwise, when $t_i\leq\deadline$, the probability is 
\begin{equation}
  p_{i, k} =
  \begin{cases}
    \Pr(y_i > y_{n-1:n-1}) & \text{if }k=1\\
    \Pr(y_{n-k+1:n-1} > y_i > y_{n-k:n-1}) & \text{if }k>1.
  \end{cases}
\end{equation}
\end{definition}

In other words, the tournament corresponds to a special case of a contest game with minimum-entry requirement in which players have a deadline to meet and the player having achieved the highest output quality within the deadline gets the first prize, the player having achieved the second highest output quality gets the second prize, and so on. 

In a similar way, we describe a race as a contest game with the following characteristics.

\begin{definition}[Race] Let $t_{(1:n-1)}, ..., t_{(n-1:n-1)}$ denote the order statistics of the $t$'s for the $n-1$ opponents of player $i$.  A race is a contest game $G$ with a minimum-entry requirement $\target>0$ where player $i$'s probability of winning a prize is zero if $y_i < \target$. Otherwise, when $y_i\geq \target$, the probability is
\begin{equation}
  p_{i, k} =
  \begin{cases}
    \Pr(t_i < t_{1:n-1}) & \text{if }k=1\\
    \Pr(t_{1-k:n-1} > t_i > t_{k:n-1}) & \text{if }k>1.
  \end{cases}
\end{equation}
\end{definition}

That is, the race corresponds to a special case where the player being the first to complete a job with a minimum quality gets the first prize, the player being the second to complete a job with a minimum quality gets the second prize, and so on.

Equilibrium
-------------

In this section, we solve the model for the equilibrium actions of players. We assume throughout that there are only two prizes of total value normalized to one, where the fraction $\alpha\geq 1/2$ goes to the first placed competitor and $1-\alpha$ goes to the second placed competitor. We also let $F_{r:n}$ and $f_{r:n}$ be the distribution and density function of the $r^{th}$ order statistic (i.e., the $r^{th}$ lowest realization) of $n$ draws from the ability distribution (i.e., the $a$'s).

### Equilibrium in a tournament

Because the probability of winning a prize in a tournament is not affected by the completion time (as soon as the deadline is met), picking a completion time equal to the deadline ($t_i=\deadline$) is a (weakly) dominant strategy for each player. Hence, from the point of view of the contest designer, imposing a more distant deadline has the same effect as a reduction in the marginal costs for everyone (i.e., proportional to the cost $\ctime(\deadline)$). [Alternatively, it can be seen as a reduction in the total value of prizes.] 

Following @moldovanu2001optimal, the (unique) symmetric equilibrium for each player $i$ is the timing $t_i^*=\deadline$ and the output quality $y_i^*=y^*(a_i)$ with the function
\begin{equation} \label{ystar}
y^*(a_i) = 
	\cscore^{-1}
	\left[\cscore(\target) 
	+ \frac{1}{\ctime(\deadline)}
	\left(\alpha \int_{a_i}^{\hitype} A(z) dz
	  + (1-\alpha) \int_{a_i}^{\hitype} B(z)  dz
	\right)
	\right]
\end{equation}
where
\begin{equation}
  A(x) = \frac{1}{c_{a}(x)} f_{(n-1:n-1)}(x)
\end{equation}
and
\begin{equation}
  B(x) = \frac{1}{c_{a}(x)} \left\{
      \left[1- F_{(n-1:n-1)}(x)\right]f_{(n-1:n-2)}(x)
      + f_{(n-1:n-1)}(x) F_{(n-1:n-2)}(x)
    \right\}.
\end{equation}
An important property of \eqref{ystar} is that it has its upper bound in XXXX and
lower bound in $y^*(\lotype) = 0$. Also, equilibrium output quality is monotonic
increasing in the agent's ability [see @moldovanu2001optimal]. Thus, using $\phi$ to denote the inverse function, the above equilibrium strategy is obtained by solving the first-order differential equation:
\begin{align}
	\label{foc0}
0 = & \alpha f_{(1:N-1)}(\phi) \phi^{\prime} 
	+ (1-\alpha)\phi^{\prime}\{[1 - F_{(1:N-1)}(\phi)]f_{(1:N-2)}(\phi) + \nonumber\\
    & + f_{(1:N-1)}(\phi) F_{(1:N-2)}(\phi)\} - c_{a}(a) c_{y}(\target) c_{t}^{\prime}(t_i)
\end{align}
with boundary condition $\phi(0) = \lotype$ (i.e., the lowest-ability competitor's optimal output quality is zero). 

Also, monotonicity of the equilibrium output quality implies that, for every $i=1, ..., n$, the equilibrium expected payoff from the contest $\pi_i^*$ depends on the rank of the player's ability relative to the others. That is, the equilibrium payoff is $\pi_i^*=\pi^*(a_i)$ with 
\begin{equation} 
	\pi^*(a_i) = \alpha F_{n:n}(a_i) + (1-\alpha)[1-F_{n:n}(a_i)] F_{n-1:n-1}(a_i)  
	- C(y^*(a_i), \deadline, a_i),
\end{equation}
where  $\pi^*(0) = 0$ and $\pi^*(\hitype) = \alpha - C(y^*(\hitype), \deadline, \hitype)>0$.

### Equilibrium in a race

In a similar way, one can derive the equilibrium strategy in a race. Because any quality that is below the minimum-entry requirement $\target$ will give a zero probability of winning and any quality that is above $\target$ is costly but gives a constant probability of winning, player $i$'s choice of optimal quality $y^*$ is either zero (with $t_i=\deadline$ by convention) or $y^*=\target$.

The (unique) symmetric equilibrium for player $i$ is the xxxxx when $xxxx$ and xxxx. 
\begin{equation}
t^* = 
	XXXX
\end{equation}
where
\begin{equation}
  A(x) = XXXX
\end{equation}
and
\begin{equation}
  B(x) = XXXX.
\end{equation}

An important property of XX is that $y^*(a_i)$ has its upper bound in XX and
lower bound in XX. Also, equilibrium output quality is monotonic
increasing in the agent’s ability [see @moldovanu2001optimal]. Thus, for
every $i=1, ..., n+1$, the equilibrium expected reward depends only on
the rank of his ability relative to the others. Using ${F_{A_{r:n}}}$ to
denote the distribution of the $r$’th order statistic of abilities gives



Hence, by setting to zero and solving for the ability, gives the
marginal ability ${\underline a}$ as

\begin{equation}
  {\underline a}= h(n, V, F_A, C, d).
\end{equation}


### Tournament vs races

By comparing equilibrium xxx and xxx, we find that the race and the tournament do not (ex-post) dominate one another with respect to output quality. Whereas the race always dominates the tournament with respect to completion time. [This is only when the deadline is the same. Otherwise, there's always xxxx.] This result is stated below.

\begin{proposition}
There always exist an interval of abilities where the output quality is higher in the race than in the tournament. By contrast, every player takes less completion time in the race than in the tournament.
\end{proposition}

\begin{proof}
Marginal type has utility zero in a race but the same type has a strictly positive utility in the tournament. Since probability of winning is not different in the race or the tournament (the bid is a monotonic transformation of the individual ability or, in other words, rankings are virtually the same), expected payoffs in equilibrium differ only in the cost functions. Hence, to be an equilibrium, the player in the tournament should bid less than the player in the race to earn a strictly positive expected payoff. 
\end{proof}

Let's make an example.  
```
p <- plnorm   # pdf individual abilities 
r <- rlnorm   # Simulate individual abilities
cy <- function(x) x^2 # Cost function performance
ct <- function(x) 2*exp(1-x)  # Cost function timing 
```
FIGURE 1. Equilibrium bids in a race and a tournament. 


Implications. The above proposition applies only if the target is higher in a race than in a tournament. But what if the two competitions had the same target ? In that case, tournaments and races have the same marginal type. Therefore, the performance of players in the tournament with reserve are always non-lower than those in the race. This does not imply that it is optimal to set the target. On the contrary, we will show that it is optimal to set an optimal target in a tournament that is below the optimal target in a race. Next section.  


The contest designer's problem
---------------------------

Let us now focus on the contest designer's problem. Imagine the contest designer can choose the competition format to be either the race or the tournament. Imagine all other aspects of design are given. The prize structure $\alpha$ has been already chosen. There is a deadline $\deadline$, which is the same in both competition formats. [The quality requirement $\target_c$ in the tournament  is smalle than that in the race $\target_\race > \target_\tournament$)] We will relax this assumption later to consider a more general setting where these variables are also part of the contest designer's problem.

The contest designer has an objective function that is increasing in the expected quality of the winning solution and decreasing in the corresponding time to completion. Here, to do not complicate exposition, we assume that the contest designer cares about the winning submission only: second placed efforts are not considered. [If the principal values the diversity of the solutions ... but we assume it does not.]


XXX EQUATION XXXX

The optimal choice involves a comparison of the expected profits between the race and the tournament. Given xxxx, we can show that there will be a threshold on the cost of completion time $\hat\tau$ above which the race is a better choice than the tournament, and vice versa.

\begin{proposition}
There's a tau above which ... 
\end{proposition}

Proof.  In a tournament, the objective function is 
\begin{align}
R_\tournament & = \Pr(t_{(1:n)}\leq \deadline) \left\{\int y^*(x \mid t_{(1:n)}\leq \deadline) dF_{n:n}(x) - \tau \deadline - 1 \right\}  \nonumber\\
  & = \int_{\mtype}^{\hitype} y^*(x) dF_{n:n}(x) - \tau \deadline - 1. 
\end{align}

That is, the contest designer's objective function is the sum of the expected output quality for a given deadline, minus the cost $\tau$ of having the winner working on the task until completion (i.e., until the deadline), and the cost of the prize pool (recall the prize pool is normalized to one). 

[Implicitly, you're assuming that the prize is always large enough to ensure positive effort.] [Second prize too is stochastic!!!!]

In a race, the objective function is
\begin{align}
R_\race & =  
  \Pr(a_{(N)}\geq \mtype) \left\{\target - \alpha -
  \Pr(a_{(N-1)}\geq \mtype) (1-\alpha) \right\}
  - \tau \int_{\mtype}^{\infty} t^*(x) dF_{N:N}(x) \nonumber\\
  & = [1-F_{N:N}(\mtype)] \left\{\target - \alpha -
  [1-F_{N-1:N}(\mtype)] (1 - \alpha) \right\}
  - \tau \int_{\mtype}^{\infty} t^*(x) dF_{N:N}(x).
\end{align}


Note. $t^*(x) \leq \deadline$ for all $x$'s. Thus, a lower bound for the above objective function can be computed: 
\begin{align}
\underline {R_\race} & = 
  [1-F_{N:N}(\mtype)] \left\{\target - \alpha -
  [1-F_{N-1:N}(\mtype)] (1 - \alpha) - \tau \deadline\right\}
\end{align}
An even simpler lower bound is rewriting the above expression as if $\alpha=1$ (note if the real alpha was set 1 then also mtype would change and therefore setting alpha hits a lower bound only when mtype does xxxx  when alpha is 1). 
 
Note. $y^*(x)$ is lower than $\target$ for all $a < \mtype$. Thus, a lower bound of the tournament's expression is
\begin{align}
\overline {R_\tournament} & = 
  [1-F_{N:N}(\mtype)] \target + \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) 
  - \tau \deadline - 1. 
\end{align}

\begin{align}
  \underline {R_\race} \geq & \overline {R_\tournament} \nonumber\\
  [1-F_{N:N}(\mtype)] (\target - 1 - \tau \deadline) \geq &
  [1-F_{N:N}(\mtype)] \target + \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) 
  - \tau \deadline - 1 \nonumber\\
  - [1-F_{N:N}(\mtype)] (\tau\deadline + 1) \geq &
  \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) 
  - (\tau \deadline + 1) \nonumber\\
  F_{N:N}(\mtype) (\tau \deadline + 1) \geq &
  \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) \nonumber\\
  \tau \geq & 
    \left[
      \frac{\int_{\mtype}^\infty y^*(x) dF_{N:N}(x)}{F_{N:N}(\mtype)} -1 
    \right] \frac{1}{\deadline}
\end{align}

End proof.

When the cost of time $\tau$ is sufficiently high, the race is preferred. Interestingly, the threshold is a function of the deadline to complete the job, as xxx. It also depends on the shape of xxxx. 

### Optimal minimum-entry

Now we turn to discuss the contest designer's choice of an optimal minimum requirement $\target$. So far, we have assumed that $\target_\race>\target_\tournament$. Now, we show that the assumption that xxxx is indeed an optimal choice of the contest designer. This is summarized in the next proposition.

\begin{proposition}
Suppose the contest designer can choose the target that max profits in both the race and the tournament. Then, the optimal $\target$ in tournament is generally lower than that in a race.
\end{proposition}

To prove that it is indeed the case. We proceed in two steps. First, we assume that the contest designer does not care about minimizing the timing of the innovation by imposing $\tau = 0$. For simplicity, assume that $\alpha=1$ (winner-takes-all). In a race, this means that the optimal target will be a value that makes equal the costs in terms of less participation versus the gains in terms of higher values of the winning solutions. Formally, the contest designer's problem in a race is
\begin{align}
  \text{maximize } & R^\race = [1-F_{N:N}(\mtype)] (\target_\race - 1).
\end{align}
Note that $\mtype$ depends on the target. This is clearly concave in $\target_\race$. 
Thus, the first order condition is also sufficient. 
\begin{align}\label{foc race}
  \text{FOC } & \Rightarrow -F^\prime_{N:N}(\mtype) \mtype^\prime (\target_\race - 1) + [1-F_{N:N}(\mtype)] = 0.
\end{align}

In a tournament, ... 
\begin{align}
  \text{maximize } & R^\race = \int_{\mtype}^\infty y^*(x, \target) d F_{N:N}(x) - [1-F_{N:N}(\mtype)]. 
\end{align}
Convexity is not sure. If not, then the optimal target is zero. Which is lower than the optimal target in a race. 

Instead. If the objective function is (strictly) concave then there's an internal solution. 

\begin{align} \label{foc tournament}
  \text{FOC } \Rightarrow & 
    \frac{d\int_{\mtype}^\infty y^*(x, \target) d F_{N:N}(x)) }{d \target}
      + F^\prime_{N:N}(\mtype) \mtype^\prime =0 \nonumber\\ 
    & \text{(by using Leibniz rule)}\nonumber\\
  \Rightarrow & - y^*(\mtype, \target) \mtype^\prime F^\prime_{N:N}(\mtype) 
      + \int_{\mtype}^\infty \dystar - F^\prime_{N:N}(\mtype) \mtype^\prime = 0\nonumber\\
  \Rightarrow & -\target \mtype^\prime F^\prime_{N:N}(\mtype) 
      + \int_{\mtype}^\infty \dystar - F^\prime_{N:N}(\mtype) \mtype^\prime = 0.
\end{align}

Using \eqref{foc race} with \eqref{foc tournament}, the optimal target is the same in the race and the tournament only if
\begin{align} 
  \int_{\mtype}^\infty \dystar = [1- F_{N:N}(\mtype)].
\end{align}

\[
  \frac{\partial y^*(x, \target)}{\partial \target} = 
    \frac{c_y^\prime(\target)}{c_y^\prime(y^*(x, \target))}. 
\]

Then. 

- If $c_y(\cdot)$ is linear, we have that the ratio is one for all $x$. 

- If $c_y(\cdot)$ is convex, then we have that it is less than one. If 

- If $c_y(\cdot)$ is concave, then we have that it is higher than one.

As a result, if linear or convex the first order condition is lower than that in the race. Since the obj. function is concave (second order is decreasing), the target should be lower in a tournament than in a race to satisfy the first order condition.  (a lower target increases the focs.).

Conjecture. If $\tau>0$, the $\target$ in the race is higher. 


Structural econometric model
----------------------------

Readings: 

- [The winner's curse, reserve prices, and endogenous entry: Empirical insights from eBay auctions][ebay]

- [Entry and competition effects in first-price auctions: theory and evidence from procurement auctions][auctions]

- [Auctions with entry][entry]

[ebay]: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.199.680&rep=rep1&type=pdf 
[entry]: http://www.vita.mcafee.cc/PDF/AuctionswithEntry.pdf
[auctions]:  https://www.econstor.eu/bitstream/10419/79263/1/516364804.pdf


General two-step strategy:

- First step. Identify the marginal type from the data and the distribution of types. 

- Second step. Using the estimated distribution of types. 


Basic idea. Equilibrium condition gives:
\begin{equation}
  y_i^* = y^*(a_i; F_{\mathcal{A}}). 
\end{equation}
with $y^*(\cdot)$ being an invertible function with $\phi$ denoting the inverse.

Hence the distribution of bids is
\begin{equation}
F_{Y}(y) = \Pr(y_i^* \leq y) 
        = \Pr(y^*(a_i) \leq y) 
        = \Pr(a_i \leq \phi(y)) 
        = F_\mathcal{A}( \phi(y)).
\end{equation}

Identification of the model. suggest
