options(digits=3)
require(stargazer)
ilogit <- function(x) exp(x)/(1+exp(x)) 
# Create panel data
summary(panel)

set.seed(4881)

# Days as factors
panel$days_f <- factor(panel$days)

# Impute missing hours!!!
panel$hours_imp <- panel$hours
index.miss <- is.na(panel$hours)
for (i in 1:4) {
	index <- panel$days==i
	h <- panel$hours_imp[index & !index.miss]
	obs <- sum(index.miss & index)
	panel$hours_imp[index.miss & index] <- sample(h, replace=FALSE, size=obs)
}

# Probability{ submission at a given date}
fit <- rep()
summary(fit$m1 <- glm(nsub>0 ~ 1, family=binomial, data=panel)) # prob. submitting 15%
summary(fit$m2 <- update(fit$m1, "~ factor(days)")) 
summary(fit$m3 <- update(fit$m1, "~ treatment + days)")) 
summary(fit$m4 <- update(fit$m1, "~ treatment + hours_imp + factor(days)")) 

stargazer(fit, type='text')

# Cumulative submissions
panel <- panel[with(panel, order(id, days)), ]
panel$nsub.cum <- with(panel, ave(nsub, id, FUN=cumsum))

# Survival (first occurrence)

# Fit an exponential model: the two fits are the same

# Compute first submission time
time.max <- "2015-03-16 11:59:59 EDT"
time.min <- "2015-03-08 12:00:00 EDT"
time.censored <- 192
fsutime <- as.numeric(difftime(races.sub$timestamp, time.min , unit='hours'))
dat <- with(races.sub, aggregate(fsutime ~ handle, FUN=min))
dat$fsu <- 1
dat2 <- merge(dat, races, by='handle', all=TRUE)
dat2$fsu[is.na(dat2$fsu)] <- 0
dat2$fsutime[is.na(dat2$fsutime)] <- time.censored


surv <- rep()
surv$m1 <- survreg(Surv(fsutime, fsu) ~ 1, dat2, dist='weibull', scale=1)
surv$m2 <- survreg(Surv(fsutime, fsu) ~ treatment + mmevents, dat2
	, dist='weibull', scale=1)
surv$m3 <- survreg(Surv(fsutime, fsu) ~ treatment + mmevents, dat2, dist='exponential')

surv$tobin <- survreg(Surv(fsutime, fsu, type='left') ~ treatment + mmevents, data=dat2, dist='gaussian')

stargazer(surv, type='text')

# A model with different baseline survival shapes for two groups, i.e.,
#   two different scale parameters
survreg(Surv(time, status) ~ ph.ecog + age + strata(sex), lung)

# There are multiple ways to parameterize a Weibull distribution. The survreg 
# function embeds it in a general location-scale family, which is a 
# different parameterization than the rweibull function, and often leads
# to confusion.
#   survreg's scale  =    1/(rweibull shape)
#   survreg's intercept = log(rweibull scale)
#   For the log-likelihood all parameterizations lead to the same value.
y <- rweibull(1000, shape=2, scale=5)
survreg(Surv(y)~1, dist="weibull")

# Economists fit a model called `tobit regression', which is a standard
# linear regression with Gaussian errors, and left censored data.
tobinfit <- survreg(Surv(durable, durable>0, type='left') ~ age + quant,
	            data=tobin, dist='gaussian')