# Introduction

Individuals, governments, and other organizations increasingly sponsor prize-based competitions to accomplish various goals---incentivize workers, raise money, and induce innovation.[^increasingly]  The design of competitions that maximize the gains of sponsoring organizations is thus becoming a topic of growing public interest. This interest has spurred a large literature focusing on various aspects of competition design such as optimal prize structures and how many competitors to admit.^[See, for example, @moldovanu2001optimal and @fullerton1999auctionin, respectively.]

[^increasingly]: @mckinsey2009 reports a boom in the extent and value of inducement prize competitions since 2000, estimating that "total funds available from large prizes have more than tripled over
the last decade to surpass $375 million."

The focus of this paper is on one relatively unexplored but important aspect of contest design: the choice between a tournament (a competition to be best) and a race (a competition to be first). Many economic situations---in the public sector, business, sports, and academia---are indeed decided by either a tournament or a race competition. Both types of competition are frequently used to procure services in the public sector, exerting a tremendous impact on economic growth;[^agriculture] to incentivize workers in companies (e.g., in the form of bonuses and promotion schemes);[^incentives]  and to increase the productivity of academic scientists (e.g., via competitive research grant awards, individual prizes).[^academia] Yet, despite such a widespread use, very little is known about how to choose between races and tournaments (and the consequences for competitors and contest sponsors). 

[^agriculture]: For example, using data on innovation tournaments sponsored by the Royal Agricultural Society of England, @Brunt:2012ix find a large effect of prizes on patents. 
[^patentraces]: See, for example, @Gallini:2002ik for a literature review on the effects of patent races on technological innovation.
[^incentives]: See, for example, @prendergast1999provision for a literature review on the provision of incentives inside firms. 
[^academia]: xxx


We argue that the choice between races and tournaments does not necessarily depend on the nature of the task under consideration. Rather it is a function of the contest designer's preferences and the strategic interactions between competitors. To see this point, consider the following real example. In 2014, after the World Health Organization (WHO) issued a report calling antimicrobial resistance[^antimicrobial] "a major threat to public health," the United Kingdom (UK) and the European Commission (EC) decided independently to sponsor two different innovation contests for accelerating the development of adequate solutions. The contest sponsored by the UK government was called the "Longitude Prize: Reduce the use of antibiotics." The one sponsored by the EC was called "Horizon prize for better use of antibiotics."  The UK's Longitude prize was a race competition: it awarded a prize to the first team to submit a solution satisfying some pre-specified effectiveness criteria (within a given submission period of 5 years). The EC's Horizon prize was, instead, a tournament: registered teams had a fixed 12-month deadline within which they could submit solutions and the best solution relative to all submissions was awarded the first prize. While both contests were dealing with the same problem (and had very similar names), the competition structure was very different from a contest design perspective, perhaps reflecting differences in underlying preferences of the contest designers. 

[^antimicrobial]: Antimicrobial resistance is "the ability of a microbe to resist the effects of medication previously used to treat them" (Wikipedia). It is often called "antibiotic" resistance because it is a phenomenon likely caused by a misuse of antibiotics. These resistant microbes are increasingly difficult to treat.


While races and tournaments are similar in various respects, it is unclear which one will dominate the other. For example, tournaments can incentivize fast solutions of high quality by fixing appropriate deadlines. However, a tournament with a "too short" deadline may implicitly raise entry costs, which in turn will reduce the competitive pressure to increase quality. For similar reasons, a race with a "too high" quality requirement might incentivize performances of higher quality, but it might also limit participation, thus reducing the competitive pressure on the time to perform the task. 

<!-- 
Though the choice between races and tournaments is sometimes dictated by external factors like tradition,[^external] contest designers face a real choice in many other situations. For the famous Netflix Prize competition, for example, the media company Netflix had to decide whether to have a race (e.g., awarding a prize to the first achieving a pre-specified accuracy target improving its movie ratings prediction algorithm) or a tournament (e.g., awarding a prize to the best approach in a given time unit). 

While the Netflix Prize competition ended up being a race, how the choice was made is still unclear. And, more in general, the existing literature does not really provide a formal decision model to help contest designers to make appropriate decisions. An issue perhaps even more relevant now that commercial platforms like Topcoder or Kaggle have emerged providing companies with different templates that facilitate the choice of various contest designs. In addition, contest designers lack any empirical evidence contrasting outcomes in races and tournaments. Our main aim with this work is hence to start filling these gaps. <!-- Understanding the consequences on outcomes of each type of competition is thus crucial for contest designers to make appropriate decisions.  
-->
 
[^external]: For example, in sports, xxxx. 
 
To examine the races vs tournaments issue from the perspective of a contest designer with preferences for time and quality of outcomes and account for the effects of this choice on contestants' strategic interactions, we proceed in two ways. Firstly, we develop a contest model that encompasses both the race and the tournament in a single framework. In particular, our approach extends the contest model introduced by @moldovanu2001optimal to a situation in which contest designers care about both the timing and quality of effort. Exploring the duality of the model, we compare equilibrium behaviors under both competitive formats and characterize the optimal choice for the contest designer. Secondly, we design and execute an experiment to test key implications of the theory in the field. More specifically, the experiment compares and contrast behaviors under three different competition regimes: races, tournaments, and tournaments with a minimum quality reserve (called tournaments with reserve). 


<!-- Why two different contest designers facing a seemingly identical problem ended up with very different choices of contest design? -->


Our approach suggests that there are two key factors that shape the decisions of contest designers. First, contest designers act to maximize their expected revenues. Expected revenues depend upon the intensity of their preferences for time and quality of effort --- e.g., developing effective solutions to antimicrobial resistance in the shortest time possible. According to these preferences, contest designers have (a) to schedule deadlines to create conditions of time pressure for contestants; and (b) select minimum criteria to avoid rewarding solutions of unsatisfying quality and (c) set up either a competition to be first or a competition to be best. By setting deadlines and minimum-quality criteria, contest designers affect the incentives for contestants to enter the competition, as well as the competitive pressure on their rivals. By choosing how contestants will compete, contest designers direct competitive pressures towards improving only one dimension of the problem, while keeping the efforts in other dimensions fixed. These different aspects --- deadlines, quality requirements, and competition styles --- interact with one another, greatly influencing the manner in which contestants behave. 

<!-- 
More generally, contest designers may care about maximizing an objective function that embeds xxxx preferences. They might also care about efficiency, when players participate in repeated .... Finally.... are strategic [How the choice affects entry of strategic players and, in turn, how entry affects final outcomes]. For example, deadlines can be used but xxx. This also impact efficiency as more entry involves more duplication costs. From the perspective of players, there is strategic equivalent but, in practice, 
 -->


Another important factor for contest designers is how the choice of tournaments vs races will affect the efficiency of the contest. In particular, one good reason to limit entry in a contest is to decrease inefficiencies like duplication costs. As suggested by @fullerton1999auctionin, it is sometimes more efficient to design contests that limit competition to only the two top contestants, instead of having an open competition. This is because having many low-skilled contestants may be just a waste of resources, as they keep essentially unaltered the competitive pressure on the top contestants while raising duplication costs. Also tournaments and races, by imposing deadlines and minimum quality requirements to win, limit competition in different ways and can be designed to deliver "efficient" results. This issue seems most relevant for firms and online platforms running multiple challenges at once among a fixed set of potential contestants, whereby seeking to implement an efficient allocation of workers/platform members to tasks.

<!-- 
One may claim that it depends on contest sponsors's preferences towards two desirable, but often incompatible, goals: $i$) maximizing revenues through raising competitors' performances while $ii$) lowering the time it takes to complete a given job. It is, however, unclear in general which of the type types of competition is more effective.  A tournament may stimulate competition that increases performance and, by having a relatively short deadline, it may also accelerate production as well. At the same time, when the deadline is set too short, it may deter entry thereby lowering the intensity of competition, which in turn may move down performance. In a similar way, races do not necessarily improve faster ... If the target is too high and xxxx. 
 
Alternatively, the choice between tournaments and races can be seen as the response to "efficiency" concerns of the contest sponsors. Under this view, races and tournaments may lead to the same expected outcomes in terms of time or effort but lead to different duplication costs by regulating "entry" into the contest [as discussed by Fullerton Mcafee, xxxx]. Hence, the "time preferences" story and the "efficiency" are two possible explanation for using a race or a contest. 

In this article, we investigate the choice between races and tournaments both theoretically, and empirically in the field.  We proceed in two 
 -->

<!-- 
To fix ideas, imagine a government willing to design an innovation contest aimed at finding solutions to a problem of public health, such as antibiotic resistance.^[This example is taken...] To minimize the risk that the threat of xxxx will materialize before a solution is found, one may choose a tournament competition format with a tight deadline for participants to provide their solutions. The problem is to find the right duration. When the duration of the competition is too short, incentives maybe insufficents for competitors to exert enough effort resulting in inadequate solutions. Alternatively, the government can set up a race competition with a prize being awarded to the first competitor who achieves, or goes beyond, a minimum quality threshold. Here the problem of accelarating the timing of innovation should not be a big issue but competitors may work inefficiently, as they have no incentives to exceed the minimum threshold.  Fixed the prize structure, both approaches have specific advantages and limitations. However, xxxx. 
 -->

Our theoretical approach follows traditional contest models, as in @moldovanu2001optimal. In this setting, contests have an all-pay structure by which participants pay an immediate cost for an uncertain future reward. The decision of timing and quality is made under the uncertainty of the costs of the rivals. The contest designer wants to maximize revenues and has preferences for both time and quality. Following the analysis of the model, we show that the optimal design depends on the number of participants and the concavity of their cost function.  We also show conditions under which races dominate tournaments--- even when the contest designer does not care about the timing --- and vice versa. We also characterize outcomes when contest designers can introduce a minimum quality reserve (i.e., tournaments with reserve) showing that tournaments with (sufficiently high) reserve always dominate races in terms of performance.

Our empirical approach involves the design and execution of a field experiment. The context of our field experiment is an online programming competition run on the online platform Topcoder at the end of 2016. In a typical programming competition, participants compete writing source code solving a given problem for winning cash prizes. We worked together with researchers from the United States National Health Institute (NIH) and the Scripps Research Institute (SCRIPPS) to select a challenging problem for the contest. The selected problem was based on an NIH's algorithm called BANNER [@leaman2008banner] that uses expert labeling to annotate abstracts of a repository of life sciences articles (e.g., PubMed), so disease characteristics can be more easily identified. The goal of the programming competition was to improve upon the current NIH's system by using a combination of expert and non-expert labeling, as described by @good2014microtask. To encourage participation, we offered $40,000 in cash prizes to participants. 

Our intervention consisted in sorting at random participants into independent virtual rooms of 10 or 15 people. These virtual rooms were then randomly assigned to one of three different competitive settings: (a) tournaments, (b) races, and (c) tournaments with reserve. Contestants were thus facing the same task to perform, same cash incentives, etc. The only difference was how they were competing against one another. 

We find that tournaments yield about $1.3$ times higher participation rates than races and tournaments with reserve, as predicted by theory. We find stark differences in terms of ability between entrants and non-entrants. But only insignificant differences in entrants between tournaments and races. That is, the conditional probability of entering the competition for a competitor with a given ability  was the same in races and tournaments. This lack of skill-based sorting does not explain the excess of entry in tournaments, suggesting other sorting mechanisms than problem-solving ability are at play.
 
We also examine treatment differences in performance. While we find only insignificant differences in the quality of outcomes across competition styles, the variance was higher in tournaments compared to races. Suggesting that, although tournaments may cost more than races on average, they are more relatively more likely to generate outcomes of very high value. At the same time, races offer other advantages, as solutions are submitted quicker in a race relative to tournaments. 

In comparing races and tournaments w/reserve, we detect a "substitution" effect as high ability competitors were more likely to enter races compared to tournaments w/reserve --- while keeping entry rates constant across the treatments. This substitution effect may explain the relatively higher volatility of outcomes in the tournaments w/reserve compared to races.

Finally, we use a structural approach to estimate our contest model. This has two main purposes (a) provide a basis for the external validity of our results to other settings and (b) enable the analysis of efficiency problems using counterfactual simulations based on the estimated model. 

Implications of these findings for contest designers are discussed at the end of this paper. 

# Literature

This paper is related to the contest theory literature in economics [@dixit1987strategic @baye2003strategic, @parreiras2010contests, @moldovanu2001optimal, @moldovanu2006contest, @siegel2009all, @siegel2014contests]. It also relates to the literature on innovation contests [@taylor1995digging, @che2003optimal]. And the personnel
economics approach to contests [@lazear1981rank, @green1983comparison, @mary1984economic].

Empirically, @dechenaux2014survey provide a comprehensive summary of the experimental literature on contests and tourments. Large body of empirical works have focused on sports contests @szymanski2003economic.
More recently, field experiments conducted inside firms have studied workers response to internal contests in terms of productivity --- individual (xxxx) and in teams  (xxxxx) --- and ideation (xxxx). A growing number of studies have also focused on similar incentives but applied to "virtual" environments like online contests (xxxx).

In our structural approach to estimate contest model, this paper follows results from classical econometrics of auctions [@paarsch1992deciding, @laffont1995econometrics, @donald1996identification] and more recent ones [@athey2011comparing, @athey2002identification, and @athey2007nonparametric].


Several aspects of contest design have been investigated, including the optimal prize structure [XXX, xxxx, xxxx], number of competitors [XXX, XXX], and imposing restrictions to competition such as minimum effort requirements [XXX, XXX]. Also, a great deal of theoretical models of races and tournaments have been developed and applied to a wide range of economic situations including patent races [xxx], arms races [xxx], sports [xxx], the mechanism of promotions inside firms [xxxx], sales tournaments [xxxx], etc.

<!-- 
There is a literature has discussed the reasons why contests are sometimes preferred to other forms of incentives (e.g., individual contracts). Typically, contests reduce monitoring costs [xxx], incentivize production with common risks [xxx], and deal with indivisible rewards [xxxx], among others. While there is not much debate on why contests should be used, the issue of how to effectively design and deploy a contest still attracts much research. 
 -->

@harris1987racing, @grossman1987dynamic investigate the dynamics issues patent races where the interest is how firms compete for a patent. @bimpikis2014designing looks at the problem of how to design an information structure that is optimal when the contest is a race and innovation is uncertain (encouragement and competition effect). In the laboratory, @zizzo2002racing finds poor support to predictions of dynamic xxxx. In general we do not know much about the dynamic aspect of contests. 

As pointed out by @baye2003strategic, many of these models of  tournament and  race competitions are specific cases of a more general "contest games." And sometimes it is possible to design one or the other in a way to exploit a "duality." This type of duality suggests that races and tournaments are "strategically equivalent" from the point of view of contestants. That is, ex-ante they might expect similar payoffs.  While  this is a very important theoretical result, it does not say how contest designers should or can exploit this duality, an issue that remains largely unknown. Relative to @baye2003strategic, we provide results on the problem of maximization of the contest designer, showing that even when tournaments and races yield same ex-ante payoff to contestants, they might not yield same payoffs (revenues) for contest designers. 


<!-- Part of the literature has been focused on the issue of economic efficiency [xxxx]. A typical finding is that contests may lead to over-expenditure of effort with participants exerting more effort than the value of the prize. This problem happens when the contest designer does not capture the entire aggregate efforts which exceeds the value of the prize. When participants have heterogeneous preferences an additional problem is that of a misallocation of the prize [xxxx]. Both isses  [we do not care.]  -->


<!-- 
By this perspective, we are able to show that races cannot be justified simply by the goal of maximizing average effort. And the reason is intuitive. A race awards a prize to first to hit a particular target. Those who will judge the target to hard to achieve will not join the competition and will drop out. On the contrary,  those who are able to achieve the target at low costs will not try to exceed the target. As a result, the race is comparable to a competition with fixed "entry costs" or a fixed entry requirement, where agents will decide to either enter and pay a fixed prize, or stay out of the competition. Then, the possible gains in terms of expected revenues from a race are limited to those who would enter the competition and would exert less effort that that required to hit the target. These potential benefits can be obtained under a tournament as well by imposing a a fixed requirement to be eligible for prizes. So, races are not chosen to maximize expected effort of competitors, at least, in the traditional "auction-theoretical" sense. 
 -->


<!-- 
In a tournament, this type of preferences can be satisfied by fixing a deadline. Say time within which competitors are asked to provide their efforts. However, assuming competitors have costs from making less time in performing a task and there complementarities in costs, increasing the deadline in a tournament is similar to raising the marginal cost for everyone, which might not be an optimal solution. In a race, by contrast, increasing the deadline will affect entry but, conditional on entry, the time to complete the task will always be less than the deadline. Which means that those with low costs will be mostly affected by the deadline, whereas xxxx.  Which may be a superior choice than the tournament.
 -->


