\newcommand\competition{c}
\newcommand\ability{a}
\newcommand\performance{y}
\newcommand\timing{t}
\newcommand\Timing{T}
\newcommand\Performance{Y}

# The model
We now generalize the contest game introduced by @moldovanu2001optimal to a situation where players simultaneously decide $i)$ how fast to perform a given task and $ii)$ the quality of their performance (e.g., the time to solve a problem and effectiveness of the solution). Then we explore the problem of revenue maximization faced by a contest designer with preferences for both time and quality.

## Basic setup
Consider a contest game where $i=1,..., n$ contestants are competing for $p$ prizes of value $v_1\geq v_2\geq ...\geq v_p\geq0$; and imagine the total value distributed to winners is normalized to one, $\sum_{k=1}^p v_k =1$. To win a prize, each contestant will act independently over the course of a given period of time $\deadline>0$ working to develop solutions to a given problem. The time it takes to develop their solutions and the effectiveness or quality of the delivered solutions are denoted by two nonnegative variables $\timing_i$ and $\performance_i$ respectively. Solving the problem can be thus defined as developing a solution with an effectiveness of at least $\target\geq0$. 

Each contestant $i$ has a cost of problem solving $c_i$ given by 
$$
	c_i = \ability_i^\alpha C(\performance_i, \timing_i)
$$ 
where $C(\cdot)$ denotes a cost function of the inputs and $a_i$ is a (strictly positive) ability parameter changing across contestants and $\alpha<0$.

The cost function $C(\cdot)$ is decreasing in the time to develop solutions. It is increasing in the quality of the developed sultions.  It is _multiplicative_ (the higher the quality the more time it takes to develop the solution at the same cost). And it is assumed to have the following functional form: $C(\performance, \timing) = \performance^\alpha \timing^\beta,$ where the parameters $\alpha>1$ and $\beta<0$ denote the _elasticity_ of the cost function with respect to its inputs.

[^speed]: Alternatively, one can re-parametrize the model by replacing time $t_i$ with a new variable "speed" $s_i$ defined as the ratio of quality over time.

The ability parameter reflects heterogeneity in skills, time constraints, and other elements affecting their ability to solve the problem. Each ability parameter $a_i$ is drawn at random from a common distribution function $F_A(\cdot)$ with (absolutely continuous) density $f_A(\cdot)$ on a bounded interval. Players observe privately the realization of their own ability (their _type_) before making their choices. 

The contest designer determines how contestants compete for prizes. We consider three types of competition: the race, tournament, and tournament with reserve. 

- In a race, the first contestant that solves the problem (i.e., achieves a performance equal or higher than $\target$) wins the first prize. The second contestant to solve the problem wins the second prize, and so on until either all the prizes are awarded or there are no more eligible contestants (i.e., those who have solved the problem in the given time). 

- In a tournament, the contestant achieving the highest performance within the given deadline $\deadline$ wins the first prize. The contestant with the second highest performance wins the second prize, and so on until all prizes are awarded.  

- Finally, the tournament with reserve is a slightly more general form of tournament competition where, to win a prize, competitors must achieve a performance equal or higher than the target $\target$. Prizes are thus awarded based on performance until either all prizes are allocated or there no more eligible contestants (i.e., those with a performance equal or higher than $\target$). 

In all three types of competition, the payoff of a contestant $i$ with ability $a_i$ who has developed a solution of quality $y_i$ that was delivered in time $t_i$, is either $v_k - \ability_i^\alpha C(y_i, t_i)$ if $i$ wins the k-th prize, or $-\ability_i^\alpha C(y_i, t_i)$ if $i$ does not win a prize.

<!-- As information is asymmetric and players move simultaneously, the quality and time of the opponents of a player $i$ can be treated as $n-1$ independent realizations of two (nonnegative) random variables $Y$ and $T$ that are drawn from some unknown distributions denoted by $F_{Y}(\cdot)$ and $F_{T}(\cdot)$ respectively. These variables help defining the individual probability of winning a prize.  -->

<!-- 
Let denote the $j$'th smallest of the order statistics of the $Y$'s by $Y_{(j)}$ ---with $Y_{(1)}$ being the smallest, $Y_{(2)}$ being the second smallest, and so on---and the $j$'th smallest of the $T$'s by $T_{(j)}$---with $T_{(1)}$ being the smallest, $T_{(2)}$ being the second smallest, and so on. The probability of winning a prize will then depend on how the rules of the contest rank-order players based on the realized values. 
 -->

<!-- 
For each player $i$'s actions $(y_i, t_i)$, the competition style of the contest determines the probability of player $i$ winning a prize and hence $i$'s expected payoffs;
\begin{equation}
		\label{expected payoffs}
		\pi_{i}^\competition 
						= \sum_{k=1}^{q} p_{i}^{k,\competition}(\performance_i, \timing_i) v_k 
						-  C(\ability_i, \performance_i, \timing_i)
\end{equation}

where $p_{i}^{k,\competition}(\cdot)$ denotes the conditional probability of winning the $k$-th prize given a performance $\performance_i$ and a completion time $\timing_i$.


In a race competition, the first player to achieve a given minimum performance target $\target$ gets the first prize, the second to achieve the same target gets the second prize, and so on.  Hence, the conditional probability of winning the $k$-th prize in a race is 

$$
	 p_{i}^{k, \text{race}}(\performance_i, \timing_i) = 
	 \begin{cases}
	 \Pr\{T_{(k-1)} < \timing_i \leq T_{(k)} \} & \text{if } \performance_i\geq\target \\
	 0 & \text{otherwise;}
	 \end{cases}
$$
 -->
 
The contest designer is risk neutral and aims to maximize its revenues by increasing the winner's performance, while keeping low the time of delivery (i.e., max the speed of production). The actions of the contest winner are random variables denoted by $(Y^w, T^w)$. The contest designer's expected payoff (net of total prizes distributed to winners) is:

$$
	\pi_{cd} = E[Y^w - \tau T^w]
$$

where $E$ denotes the expectation with respect to the distribution of players' actions in equilibrium; and $\tau$ denotes the intensity of the contest designer's (negative) preferences towards solutions delivered later in time.

<!-- For simplicity, assume the total prizes distributed in the contest (either paid or not to winners) are sunk.  -->

## Equilibrium
We now solve the model for the unique symmetric Bayesian Nash equilibrium of players.

### Races
The first key observation is that, in a race, any solution of quality below the target $\target$ gives a zero probability of winning prizes; and any solution of quality above the target gives a constant probability of winning. It is thus a dominant strategy for every contestant to choose a quality either of zero (i.e., the lowest possible) or equal to the target $\target$.^[As choosing a quality of zero gives a null payoff for any $t$, we use the convention that when $y_i=0$ then $t_i = \deadline$ to avoid multiplicity of equilibria.]

Since contestants act independently, for each contestant $i$ the actions of its opponents can be treated like realizations of the random variables $Y$ and $T$ that are independently drawn from the distributions $F_Y$ for time and $F_T$ for quality. 

Let denote the $j$'th smallest of the $T$'s by $T_{(j)}$, with $T_{(1)}$ being the smallest, $T_{(2)}$ being the second smallest, and so on. For each contestant $i$ with a timing $t_i$, the probability of winning the first prize is:
$$
	Pr(\text{winning first prize})
		 = Pr(t_i \leq T_{(1)}) = 1 - F_{T_{(1)}}(t_i);
$$
the probability of winning the second prize is:
$$
	Pr(\text{winning second prize}) 
		= Pr( T_{(1)} < t_i \leq T_{(2)}) =  F_{T_{(1)}}(t_i) [1- F_{T_{(1,n-2)}}(t_i)];
$$
and so on.

<!-- 
Let denote the $j$'th smallest of the $Y$'s by $Y_{(j)}$ ---with $Y_{(1)}$ being the smallest, $Y_{(2)}$ being the second smallest, and so on---and the $j$'th smallest of the $T$'s by $T_{(j)}$---with $T_{(1)}$ being the smallest, $T_{(2)}$ being the second smallest, and so on. The probability of winning a prize will then depend on how the rules of the contest rank-order players based on the realized values. 
 -->

Assuming there exists a monotonic function $t^*(\cdot)$, we use  change of variable to express xxxx into axxxx. Then the optimal action for contestant $i$ is xxxx. 

that the optimal timing $t_i^*$ for a player with ability $a_i$ is $t^*_i = t^*(a_i)$. The optimal timing $t_i^*$ is given by first order conditions
$$
	\frac{d g(\phi)}{d \phi} \dot\phi = a^\alpha y^\beta \delta t^{\delta-1}
$$

Using the definition: 
$$
	\frac{d \phi}{d y} =  g(\phi) h(t)
$$
where 
$$
	g(\phi) = \phi^\alpha \left[\sum \dot p^k (\phi) v_k \right]^{-1}
$$
and
$$
	h(y) =  \target^\beta  \delta t^{\delta -1}
$$
with initial conditions $\phi(\deadline)=0$. 

Here, the key observation is that, for a given level of quality, any time that is strictly below the deadline does not affect the probability of winning but is costly in terms of effort (working faster is costlier) and any time that is strictly above the deadline gives a negative payoff. Thus, choosing  $t_i=\deadline$ is a (weakly) dominant strategy for each player. Then the first order condition with respect to quality is:

\[
	\sum_{k=1}^{q} \hat p^{\prime}_{k}(y_i) v_k = \cability(a_i) \cscore^\prime(y_i) \ctime(\deadline).
\]

where $\hat p = p(\cdot, \deadline).$ Then it can be show that xxxx. 


<!---
 also means that, from the point of view of the contest designer, imposing a more distant deadline has the same effect as a reduction in the marginal costs for every participant competitor. [This should go later] Then, the equilibrium $y_i$ must xxx a monotonic function $y^*()$ with an inverse $\phi()$ which satisfies the first-order differential equation
-->

\begin{align}
0 = & \alpha f_{(1:N-1)}(\phi) \phi^{\prime} 
	+ (1-\alpha)\phi^{\prime}\{[1 - F_{(1:N-1)}(\phi)]f_{(1:N-2)}(\phi) + \nonumber\\
    & + f_{(1:N-1)}(\phi) F_{(1:N-2)}(\phi)\} 
    - c_{a}(a) c_{y}(\target) \ctime^{\prime}(t_i)
\end{align}

subject to the boundary condition  $\phi(0) = \lotype$ (i.e., the lowest-ability competitor's optimal output quality is zero). 

As shown by @moldovanu2001optimal, the solution is 

\begin{equation} \label{ystar}
y^*(a_i) = 
	\cscore^{-1}
	\left[\cscore(\target) 
	+ \frac{1}{\ctime(\deadline)}
	\left(\alpha \int_{a_i}^{\hitype} A(z) dz
	  + (1-\alpha) \int_{a_i}^{\hitype} B(z)  dz
	\right)
	\right]
\end{equation}
where
\begin{equation}
  A(x) = \frac{1}{c_{a}(x)} f_{(n-1:n-1)}(x)
\end{equation}
and
\begin{equation}
  B(x) = \frac{1}{c_{a}(x)} \left\{
      \left[1- F_{(n-1:n-1)}(x)\right]f_{(n-1:n-2)}(x)
      + f_{(n-1:n-1)}(x) F_{(n-1:n-2)}(x)
    \right\}.
\end{equation}
 
Monotonicity of the equilibrium output quality implies that, for every $i=1, ..., n$, the equilibrium expected payoff from the contest $\pi_i^*$ depends on the rank of the player's ability relative to the others. As a result, the equilibrium expected payoff net of costs is
\begin{equation} 
	R(a_i) = \alpha F_{n:n}(a_i) + (1-\alpha)[1-F_{n:n}(a_i)] F_{n-1:n-1}(a_i).
\end{equation} % payoffs


### Equilibrium in a race

In a similar way, one can derive the equilibrium strategy in a race. Again the key observation is that any quality below the target gives a zero probability of winning and any quality  above the target gives a constant probability of winning. Thus, player $i$'s choice of optimal quality $y^*$ is either zero (with $t_i=\deadline$ by convention) or $y^*=\target$.

Then, the equilibrium xxx for player $i$ is 
\begin{equation} \label{tstar}
t^*(a_i) = 
	\ctime^{-1}
	\left[\ctime(\deadline) 
	+ \frac{1}{\cscore(\target)}
	\left(\alpha \int_{a_i}^{\hitype} A^\prime(z) dz
	  + (1-\alpha) \int_{a_i}^{\hitype} B^\prime(z)  dz
	\right)
	\right]
\end{equation}
where
\begin{equation}
  A(x) = \frac{1}{c_{a}(x)} f_{(n-1:n-1)}(x)
\end{equation}
and
\begin{equation}
	B(x) = \frac{1}{c_{a}(x)} \left\{
      		\left[1- F_{(n-1:n-1)}(x)\right]f_{(n-1:n-2)}(x)
      		+ f_{(n-1:n-1)}(x) F_{(n-1:n-2)}(x)
    \right\}.
\end{equation}

An important property of XX is that $y^*(a_i)$ has its upper bound in XX and
lower bound in XX. Again payoffs are xxxx. Hence, by setting to zero and solving for the ability, gives the marginal ability ${\underline a}$ as
\begin{equation}
  {\underline a}= h(n, V, F_A, C, d).
\end{equation}

### Tournament vs races

By comparing equilibrium xxx and xxx, we find that the race and the tournament do not (ex-post) dominate one another with respect to output quality. Whereas the race always dominates the tournament with respect to completion time. [This is only when the deadline is the same. Otherwise, there's always xxxx.] This result is stated below.

\begin{proposition}
There always exist an interval of abilities where the output quality is higher in the race than in the tournament. By contrast, every player takes less completion time in the race than in the tournament.
\end{proposition}

\begin{proof}
Marginal type has utility zero in a race but the same type has a strictly positive utility in the tournament. Since probability of winning is not different in the race or the tournament (the bid is a monotonic transformation of the individual ability or, in other words, rankings are virtually the same), expected payoffs in equilibrium differ only in the cost functions. Hence, to be an equilibrium, the player in the tournament should bid less than the player in the race to earn a strictly positive expected payoff. 
\end{proof}

Let's make an example.  
```
p <- plnorm   # pdf individual abilities 
r <- rlnorm   # Simulate individual abilities
cy <- function(x) x^2 # Cost function performance
ct <- function(x) 2*exp(1-x)  # Cost function timing 
```
FIGURE 1. Equilibrium bids in a race and a tournament. 


Implications. The above proposition applies only if the target is higher in a race than in a tournament. But what if the two competitions had the same target ? In that case, tournaments and races have the same marginal type. Therefore, the performance of players in the tournament with reserve are always non-lower than those in the race. This does not imply that it is optimal to set the target. On the contrary, we will show that it is optimal to set an optimal target in a tournament that is below the optimal target in a race. Next section.  


## The contest designer's problem

Let us now focus on the contest designer's problem. Imagine the contest designer can choose the competition format to be either the race or the tournament. Imagine all other aspects of design are given. The prize structure $\alpha$ has been already chosen. There is a deadline $\deadline$, which is the same in both competition formats. [The quality requirement $\target_c$ in the tournament  is smalle than that in the race $\target_\race > \target_\tournament$)] We will relax this assumption later to consider a more general setting where these variables are also part of the contest designer's problem.

The contest designer has an objective function that is increasing in the expected quality of the winning solution and decreasing in the corresponding time to completion. Here, to do not complicate exposition, we assume that the contest designer cares about the winning submission only: second placed efforts are not considered. [If the principal values the diversity of the solutions ... but we assume it does not.]


XXX EQUATION XXXX

The optimal choice involves a comparison of the expected profits between the race and the tournament. Given xxxx, we can show that there will be a threshold on the cost of completion time $\hat\tau$ above which the race is a better choice than the tournament, and vice versa.

\begin{proposition}
There's a tau above which ... 
\end{proposition}

Proof.  In a tournament, the objective function is 
\begin{align}
R_\tournament & = \Pr(t_{(1:n)}\leq \deadline) \left\{\int y^*(x \mid t_{(1:n)}\leq \deadline) dF_{n:n}(x) - \tau \deadline - 1 \right\}  \nonumber\\
  & = \int_{\mtype}^{\hitype} y^*(x) dF_{n:n}(x) - \tau \deadline - 1. 
\end{align}

That is, the contest designer's objective function is the sum of the expected output quality for a given deadline, minus the cost $\tau$ of having the winner working on the task until completion (i.e., until the deadline), and the cost of the prize pool (recall the prize pool is normalized to one). 

[Implicitly, you're assuming that the prize is always large enough to ensure positive effort.] [Second prize too is stochastic!!!!]

In a race, the objective function is
\begin{align}
R_\race & =  
  \Pr(a_{(N)}\geq \mtype) \left\{\target - \alpha -
  \Pr(a_{(N-1)}\geq \mtype) (1-\alpha) \right\}
  - \tau \int_{\mtype}^{\infty} t^*(x) dF_{N:N}(x) \nonumber\\
  & = [1-F_{N:N}(\mtype)] \left\{\target - \alpha -
  [1-F_{N-1:N}(\mtype)] (1 - \alpha) \right\}
  - \tau \int_{\mtype}^{\infty} t^*(x) dF_{N:N}(x).
\end{align}


Note. $t^*(x) \leq \deadline$ for all $x$'s. Thus, a lower bound for the above objective function can be computed: 
\begin{align}
\underline {R_\race} & = 
  [1-F_{N:N}(\mtype)] \left\{\target - \alpha -
  [1-F_{N-1:N}(\mtype)] (1 - \alpha) - \tau \deadline\right\}
\end{align}
An even simpler lower bound is rewriting the above expression as if $\alpha=1$ (note if the real alpha was set 1 then also mtype would change and therefore setting alpha hits a lower bound only when mtype does xxxx  when alpha is 1). 
 
Note. $y^*(x)$ is lower than $\target$ for all $a < \mtype$. Thus, a lower bound of the tournament's expression is
\begin{align}
\overline {R_\tournament} & = 
  [1-F_{N:N}(\mtype)] \target + \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) 
  - \tau \deadline - 1. 
\end{align}

\begin{align}
  \underline {R_\race} \geq & \overline {R_\tournament} \nonumber\\
  [1-F_{N:N}(\mtype)] (\target - 1 - \tau \deadline) \geq &
  [1-F_{N:N}(\mtype)] \target + \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) 
  - \tau \deadline - 1 \nonumber\\
  - [1-F_{N:N}(\mtype)] (\tau\deadline + 1) \geq &
  \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) 
  - (\tau \deadline + 1) \nonumber\\
  F_{N:N}(\mtype) (\tau \deadline + 1) \geq &
  \int_{\mtype}^\infty y^*(x) dF_{N:N}(x) \nonumber\\
  \tau \geq & 
    \left[
      \frac{\int_{\mtype}^\infty y^*(x) dF_{N:N}(x)}{F_{N:N}(\mtype)} -1 
    \right] \frac{1}{\deadline}
\end{align}

End proof.

When the cost of time $\tau$ is sufficiently high, the race is preferred. Interestingly, the threshold is a function of the deadline to complete the job, as xxx. It also depends on the shape of xxxx. 

### Optimal minimum-entry

Now we turn to discuss the contest designer's choice of an optimal minimum requirement $\target$. So far, we have assumed that $\target_\race>\target_\tournament$. Now, we show that the assumption that xxxx is indeed an optimal choice of the contest designer. This is summarized in the next proposition.

\begin{proposition}
Suppose the contest designer can choose the target that max profits in both the race and the tournament. Then, the optimal $\target$ in tournament is generally lower than that in a race.
\end{proposition}

To prove that it is indeed the case. We proceed in two steps. First, we assume that the contest designer does not care about minimizing the timing of the innovation by imposing $\tau = 0$. For simplicity, assume that $\alpha=1$ (winner-takes-all). In a race, this means that the optimal target will be a value that makes equal the costs in terms of less participation versus the gains in terms of higher values of the winning solutions. Formally, the contest designer's problem in a race is
\begin{align}
  \text{maximize } & R^\race = [1-F_{N:N}(\mtype)] (\target_\race - 1).
\end{align}
Note that $\mtype$ depends on the target. This is clearly concave in $\target_\race$. 
Thus, the first order condition is also sufficient. 
\begin{align}\label{foc race}
  \text{FOC } & \Rightarrow -F^\prime_{N:N}(\mtype) \mtype^\prime (\target_\race - 1) + [1-F_{N:N}(\mtype)] = 0.
\end{align}

In a tournament, ... 
\begin{align}
  \text{maximize } & R^\race = \int_{\mtype}^\infty y^*(x, \target) d F_{N:N}(x) - [1-F_{N:N}(\mtype)]. 
\end{align}
Convexity is not sure. If not, then the optimal target is zero. Which is lower than the optimal target in a race. 

Instead. If the objective function is (strictly) concave then there's an internal solution. 

\begin{align} \label{foc tournament}
  \text{FOC } \Rightarrow & 
    \frac{d\int_{\mtype}^\infty y^*(x, \target) d F_{N:N}(x)) }{d \target}
      + F^\prime_{N:N}(\mtype) \mtype^\prime =0 \nonumber\\ 
    & \text{(by using Leibniz rule)}\nonumber\\
  \Rightarrow & - y^*(\mtype, \target) \mtype^\prime F^\prime_{N:N}(\mtype) 
      + \int_{\mtype}^\infty \dystar - F^\prime_{N:N}(\mtype) \mtype^\prime = 0\nonumber\\
  \Rightarrow & -\target \mtype^\prime F^\prime_{N:N}(\mtype) 
      + \int_{\mtype}^\infty \dystar - F^\prime_{N:N}(\mtype) \mtype^\prime = 0.
\end{align}

Using \eqref{foc race} with \eqref{foc tournament}, the optimal target is the same in the race and the tournament only if
\begin{align} 
  \int_{\mtype}^\infty \dystar = [1- F_{N:N}(\mtype)].
\end{align}

\[
  \frac{\partial y^*(x, \target)}{\partial \target} = 
    \frac{c_y^\prime(\target)}{c_y^\prime(y^*(x, \target))}. 
\]

Then. 

- If $c_y(\cdot)$ is linear, we have that the ratio is one for all $x$. 

- If $c_y(\cdot)$ is convex, then we have that it is less than one. If 

- If $c_y(\cdot)$ is concave, then we have that it is higher than one.

As a result, if linear or convex the first order condition is lower than that in the race. Since the obj. function is concave (second order is decreasing), the target should be lower in a tournament than in a race to satisfy the first order condition.  (a lower target increases the focs.).

Conjecture. If $\tau>0$, the $\target$ in the race is higher. 


## Structural econometric model

Readings: 

- [The winner's curse, reserve prices, and endogenous entry: Empirical insights from eBay auctions][ebay]

- [Entry and competition effects in first-price auctions: theory and evidence from procurement auctions][auctions]

- [Auctions with entry][entry]

[ebay]: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.199.680&rep=rep1&type=pdf 
[entry]: http://www.vita.mcafee.cc/PDF/AuctionswithEntry.pdf
[auctions]:  https://www.econstor.eu/bitstream/10419/79263/1/516364804.pdf


General two-step strategy:

- First step. Identify the marginal type from the data and the distribution of types. 

- Second step. Using the estimated distribution of types. 


Basic idea. Equilibrium condition gives:
\begin{equation}
  y_i^* = y^*(a_i; F_{\mathcal{A}}). 
\end{equation}
with $y^*(\cdot)$ being an invertible function with $\phi$ denoting the inverse.

Hence the distribution of bids is
\begin{equation}
F_{Y}(y) = \Pr(y_i^* \leq y) 
        = \Pr(y^*(a_i) \leq y) 
        = \Pr(a_i \leq \phi(y)) 
        = F_\mathcal{A}( \phi(y)).
\end{equation}

Identification of the model. suggest
