
# Discussion

[TBA]


**Entry** Overall, and consistent with theoretical predictions, we found evidence that competitors in tournaments had higher propensity to enter the competition relative to those randomly assigned to the other treatments. While our data show stark differences between entrants and non-entrants, we did not detect significant differences in entrants' characteristics between races and tournaments. Both conditional and unconditional differences in means between races and tournaments are insignificant. In particular, we found no evidence of skill-based sorting between races and tournaments.  By contrast, we found significant differences in entrants' characteristics between races and tournaments with reserve. Since entry rates are not different between these two treatment groups, a substitution effect must have occurred, which was unexpected as not predicted by theory.


**productivity** Taken together, these results show that races and tournaments had equivalent productivity. At the same time, the productivity per dollar spent was higher in races. This is because the task was such that many competitors failed to reach a desired target performance resulting in larger payouts in tournaments where achieving the desired target was required. This finding suggests that, at least in our setting, races would be a more "efficient" choice of design than tournaments. Contrary to expectations, tournaments with reserve failed to deliver higher productivity levels, although they exhibited significantly higher variance relative to the other treatments. An issue that will discuss later. 
